### ISSUE TITLE
Exception in TaskManager

### ISSUE THREAD

**Issue by andrewlock** [nopSolutions/nopCommerce#1760]
## Summary
I am periodically seeing an exception - `The requested service 'Nop.Services.Tasks.IScheduleTaskService' has not been registered`

## Details
I am currently in the process of upgrading a site from 3.70 to 3,80 and am having a few difficulties with an exception occurring in TaskManager.

Periodically, I get the 'An exception has occurred in w3wp.exe' 'choose a debugger' popup when working with the upgraded site. It appears AutoFac is unable to resolve the `IScheduleTaskService` as part of running a task.

There is no relevant customisation to the base nop code, and everything else about the site is functioning correctly as far as I can tell. Services are being resolved correctly in general, and the `ScheduleTaskService` is definitely registered in Nop.Web.Framework\DependencyRegistrar.cs with an  `InstancePerLifetimeScope` lifetime.

The scope at the point the exception occurs is `Tag = "AutofacWebRequest", Disposed = false`, but it appears to be missing the majority of registration sources and Regsistrations (normally 10 sources and 618 registrations, with the exception 1 Source and 8 Regsitrations)

The exception itself is show below:

```
Autofac.Core.Registration.ComponentNotRegisteredException was unhandled
  HResult=-2146233088
  Message=The requested service 'Nop.Services.Tasks.IScheduleTaskService' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.
  Source=Autofac
  StackTrace:
       at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
       at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
       at Nop.Core.Infrastructure.DependencyManagement.ContainerManager.Resolve[T](String key, ILifetimeScope scope) in C:\Projects\Repos\nopcommerce\Source\Libraries\Nop.Core\Infrastructure\DependencyManagement\ContainerManager.cs:line 54
       at Nop.Services.Tasks.Task.Execute(Boolean throwException, Boolean dispose, Boolean ensureRunOnOneWebFarmInstance) in C:\Projects\Repos\nopcommerce\Source\Libraries\Nop.Services\Tasks\Task.cs:line 79
       at Nop.Services.Tasks.TaskThread.Run() in C:\Projects\Repos\nopcommerce\Source\Libraries\Nop.Services\Tasks\TaskThread.cs:line 32
       at Nop.Services.Tasks.TaskThread.TimerHandler(Object state) in C:\Projects\Repos\nopcommerce\Source\Libraries\Nop.Services\Tasks\TaskThread.cs:line 40
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.TimerQueueTimer.CallCallback()
       at System.Threading.TimerQueueTimer.Fire()
       at System.Threading.TimerQueue.FireNextTimers()
  InnerException: 
```

**Comment by andrewlock** [comment]
Actually, I've just discovered the problem and you've already fixed it in e987f90ae926ffa9681f6afebccc6c071b2be421. I had pulled in the automapper plugin fix and the bug was in that new code as the container was being recreated empty when dependencies were mapped.

Closing as already fixed
