### ISSUE TITLE
Occasional exception with "closed connection" in schedule tasks

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#1800]
Periodically this exception occurs in the method  GetAllStores() during schedule tasks execution.

Looks like the connection is closed and them immediately opened (code can run fine after exception)

```
System.Data.Entity.Core.EntityCommandExecutionException was unhandled
  HResult=-2146232004
  Message=An error occurred while executing the command definition. See the inner exception for details.
  Source=EntityFramework
  StackTrace:
       at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
       at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
       at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()
       at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
       at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
       at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
       at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
       at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
       at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       at Nop.Services.Stores.StoreService.<GetAllStores>b__8_0() in \src\Libraries\Nop.Services\Stores\StoreService.cs:line 98
       at Nop.Core.Caching.CacheExtensions.Get[T](ICacheManager cacheManager, String key, Int32 cacheTime, Func`1 acquire) in \src\Libraries\Nop.Core\Caching\Extensions.cs:line 42
       at Nop.Core.Caching.CacheExtensions.Get[T](ICacheManager cacheManager, String key, Func`1 acquire) in \src\Libraries\Nop.Core\Caching\Extensions.cs:line 23
       at Nop.Services.Stores.StoreService.GetAllStores() in \src\Libraries\Nop.Services\Stores\StoreService.cs:line 93
       at Nop.Web.Framework.WebStoreContext.get_CurrentStore() in \src\Presentation\Nop.Web.Framework\WebStoreContext.cs:line 37
       at Nop.Core.WebHelper.GetStoreHost(Boolean useSsl) in \src\Libraries\Nop.Core\WebHelper.cs:line 295
       at Nop.Core.WebHelper.GetThisPageUrl(Boolean includeQueryString, Boolean useSsl) in \src\Libraries\Nop.Core\WebHelper.cs:line 196
       at Nop.Core.WebHelper.GetThisPageUrl(Boolean includeQueryString) in \src\Libraries\Nop.Core\WebHelper.cs:line 179
       at Nop.Services.Logging.DefaultLogger.InsertLog(LogLevel logLevel, String shortMessage, String fullMessage, Customer customer) in \src\Libraries\Nop.Services\Logging\DefaultLogger.cs:line 224
       at Nop.Services.Logging.LoggingExtensions.FilteredLog(ILogger logger, LogLevel level, String message, Exception exception, Customer customer) in \src\Libraries\Nop.Services\Logging\LoggingExtensions.cs:line 39
       at Nop.Services.Logging.LoggingExtensions.Error(ILogger logger, String message, Exception exception, Customer customer) in \src\Libraries\Nop.Services\Logging\LoggingExtensions.cs:line 23
       at Nop.Services.Tasks.Task.Execute(Boolean throwException, Boolean dispose, Boolean ensureRunOnOneWebFarmInstance) in \src\Libraries\Nop.Services\Tasks\Task.cs:line 136
       at Nop.Services.Tasks.TaskThread.Run() in \src\Libraries\Nop.Services\Tasks\TaskThread.cs:line 32
       at Nop.Services.Tasks.TaskThread.TimerHandler(Object state) in \src\Libraries\Nop.Services\Tasks\TaskThread.cs:line 40
       at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.TimerQueueTimer.CallCallback()
       at System.Threading.TimerQueueTimer.Fire()
       at System.Threading.TimerQueue.FireNextTimers()
       at System.Threading.TimerQueue.AppDomainTimerCallback()
  InnerException: 
       HResult=-2146233079
       Message=Invalid operation. The connection is closed.
       Source=System.Data
       StackTrace:
            at System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
            at System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
            at System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
            at System.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)
            at System.Data.SqlClient.TdsParserStateObject.TryPeekByte(Byte& value)
            at System.Data.SqlClient.SqlDataReader.TrySetMetaData(_SqlMetaDataSet metaData, Boolean moreInfo)
            at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
            at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
            at System.Data.SqlClient.SqlDataReader.get_MetaData()
            at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
            at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
            at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
            at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
            at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
            at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
            at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
            at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<Reader>b__c(DbCommand t, DbCommandInterceptionContext`1 c)
            at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
            at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
            at System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
            at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
            at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
       InnerException: 

```

**Comment by RomanovM** [comment]
Another similar error:
```
Autofac.Core.DependencyResolutionException was unhandled
  HResult=-2146233088
  Message=An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = DefaultLogger (ReflectionActivator), Services = [Nop.Services.Logging.ILogger], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = CommonSettings (DelegateActivator), Services = [Nop.Core.Domain.Common.CommonSettings], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred while executing the command definition. See the inner exception for details. (See inner exception for details.) (See inner exception for details.)
  Source=Autofac
  StackTrace:
       at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
       at Autofac.Core.Resolving.InstanceLookup.<Execute>b__5_0()
       at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
       at Autofac.Core.Resolving.InstanceLookup.Execute()
       at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
       at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
       at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
       at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
       at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
       at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
       at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context)
       at Nop.Core.Infrastructure.DependencyManagement.ContainerManager.Resolve[T](String key, ILifetimeScope scope) in \src\Libraries\Nop.Core\Infrastructure\DependencyManagement\ContainerManager.cs:line 54
       at Nop.Services.Tasks.Task.Execute(Boolean throwException, Boolean dispose, Boolean ensureRunOnOneWebFarmInstance) in \src\Libraries\Nop.Services\Tasks\Task.cs:line 135
       at Nop.Services.Tasks.TaskThread.Run() in \src\Libraries\Nop.Services\Tasks\TaskThread.cs:line 32
       at Nop.Services.Tasks.TaskThread.TimerHandler(Object state) in \src\Libraries\Nop.Services\Tasks\TaskThread.cs:line 40
       at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.TimerQueueTimer.CallCallback()
       at System.Threading.TimerQueueTimer.Fire()
       at System.Threading.TimerQueue.FireNextTimers()
       at System.Threading.TimerQueue.AppDomainTimerCallback()
  InnerException: 
       HResult=-2146233088
       Message=An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = CommonSettings (DelegateActivator), Services = [Nop.Core.Domain.Common.CommonSettings], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred while executing the command definition. See the inner exception for details. (See inner exception for details.)
       Source=Autofac
       StackTrace:
            at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
            at Autofac.Core.Resolving.InstanceLookup.<Execute>b__5_0()
            at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
            at Autofac.Core.Resolving.InstanceLookup.Execute()
            at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
            at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
            at Autofac.Core.Activators.Reflection.AutowiringParameter.<>c__DisplayClass0_0.<CanSupplyValue>b__0()
            at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
            at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
            at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
       InnerException: 
            HResult=-2146232004
            Message=An error occurred while executing the command definition. See the inner exception for details.
            Source=EntityFramework
            StackTrace:
                 at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
                 at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
                 at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()
                 at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
                 at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
                 at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
                 at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
                 at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
                 at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
                 at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
                 at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
                 at Nop.Services.Stores.StoreService.<GetAllStores>b__8_0() in \src\Libraries\Nop.Services\Stores\StoreService.cs:line 98
                 at Nop.Core.Caching.CacheExtensions.Get[T](ICacheManager cacheManager, String key, Int32 cacheTime, Func`1 acquire) in \src\Libraries\Nop.Core\Caching\Extensions.cs:line 42
                 at Nop.Core.Caching.CacheExtensions.Get[T](ICacheManager cacheManager, String key, Func`1 acquire) in \src\Libraries\Nop.Core\Caching\Extensions.cs:line 23
                 at Nop.Services.Stores.StoreService.GetAllStores() in \src\Libraries\Nop.Services\Stores\StoreService.cs:line 93
                 at Nop.Web.Framework.WebStoreContext.get_CurrentStore() in \src\Presentation\Nop.Web.Framework\WebStoreContext.cs:line 37
                 at Nop.Web.Framework.SettingsSource.<>c__2`1.<BuildRegistration>b__2_0(IComponentContext c, IEnumerable`1 p) in \src\Presentation\Nop.Web.Framework\DependencyRegistrar.cs:line 393
                 at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass0_0`1.<ForDelegate>b__0(IComponentContext c, IEnumerable`1 p)
                 at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
                 at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
            InnerException: 
                 HResult=-2146233079
                 Message=Invalid operation. The connection is closed.
                 Source=System.Data
                 StackTrace:
                      at System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
                      at System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
                      at System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
                      at System.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)
                      at System.Data.SqlClient.TdsParserStateObject.TryPeekByte(Byte& value)
                      at System.Data.SqlClient.SqlDataReader.TrySetMetaData(_SqlMetaDataSet metaData, Boolean moreInfo)
                      at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
                      at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
                      at System.Data.SqlClient.SqlDataReader.get_MetaData()
                      at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
                      at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
                      at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
                      at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
                      at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
                      at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
                      at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
                      at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<Reader>b__c(DbCommand t, DbCommandInterceptionContext`1 c)
                      at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
                      at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
                      at System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
                      at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
                      at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
                 InnerException: 

```
