### ISSUE TITLE
SquareUp Plugin breaks checkout process

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#2738]
Hi, I am on 4.00 and the new SquareUp plug in breaks my production application. It runs on my localhost and I get the same thing, but I can't seem to track it down.

When I click "Checkout" from my "Cart" I get the error:
`fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: The path in 'value' must start with '/'.
      Parameter name: value
System.ArgumentException: The path in 'value' must start with '/'.
Parameter name: value
   at Microsoft.AspNetCore.Http.PathString..ctor(String value)
   at Nop.Web.Framework.UI.PageHeadBuilder.GenerateScripts(IUrlHelper urlHelper, ResourceLocation location, Nullable`1 bundleFiles)
   at Nop.Web.Framework.UI.LayoutExtensions.NopScripts(IHtmlHelper html, IUrlHelper urlHelper, ResourceLocation location, Nullable`1 bundleFiles)
   at AspNetCore._Views_Shared__Root_Head_cshtml.<<ExecuteAsync>b__9_2>d.MoveNext() in C:\HostingSpaces\ochapparel\ochapparel.com\wwwroot\Views\Shared\_Root.Head.cshtml:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.<SetOutputContentAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at AspNetCore._Views_Shared__Root_Head_cshtml.<ExecuteAsync>d__9.MoveNext() in C:\HostingSpaces\ochapparel\ochapparel.com\wwwroot\Views\Shared\_Root.Head.cshtml:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageCoreAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---`

When I disable SquareUp plugin, the page renders fine

Source: https://www.nopcommerce.com/boards/t/49614/nops-version-of-squareup-breaks-checkout-page.aspx

**Comment by Ochapparel** [comment]
Appears to be failing in Nop.Web.Framework - UI - PageHeadBuilder.cs at line 348 when dealing with https://js.squareup.com/v2/paymentform

When it gets to adding that it bombs out.

**Comment by Ochapparel** [comment]
Found a work around. I had to download the JS from "https://js.squareup.com/v2/paymentform" and copy it into `Nop.Plugin.Payments.Square\Content\paymentform.js`

Then had to update these locations:
**Nop.Plugin.Payments.Square\Views\PaymentInfo.cshtml(4)**
_From_
`Html.AddScriptParts(ResourceLocation.Footer, "https://js.squareup.com/v2/paymentform");`

_To_
`Html.AddScriptParts(ResourceLocation.Footer, "~/Plugins/Payments.Square/Content/paymentform.js");`


**Nop.Plugin.Payments.Square\Services\EventConsumer.cs(66)**
_From_
`eventMessage.Helper.AddScriptParts(ResourceLocation.Footer, "https://js.squareup.com/v2/paymentform");`

_To_
`eventMessage.Helper.AddScriptParts(ResourceLocation.Footer, "~/Plugins/Payments.Square/Content/paymentform.js");`


Not sure if this is the proper way to accomplish this. It would be best to have it pull from Square...but I'm not sure how.

**Comment by AndreiMaz** [comment]
Do you have js minification enabled?

**Comment by Ochapparel** [comment]
I do not believe so. I use google chrome. How can I check?

**Comment by AndreiMaz** [comment]
please see admin area > configuration > general settings > js minification. is ti enabled?

**Comment by Ochapparel** [comment]
Yes it IS enabled

**Comment by AndreiMaz** [comment]
https://www.nopcommerce.com/boards/t/49614/nops-version-of-squareup-breaks-checkout-page.aspx
