### ISSUE TITLE
Logger exception about Id

### ISSUE THREAD

**Issue by ArturAlekseev** [nopSolutions/nopCommerce#2742]
Strange thing. I'v started to debug Admin part and often get this exception:
```
public virtual void Insert(T entity)
        {
            try
            {
                if (entity == null)
                    throw new ArgumentNullException(nameof(entity));

                Entities.Add(entity);

                _context.SaveChanges(); //**HERE**
            }
            catch (DbEntityValidationException dbEx)
            {
                //ensure that the detailed error text is saved in the Log
                throw new Exception(GetFullErrorTextAndRollbackEntityChanges(dbEx), dbEx);
            }
        }
```

When system tries to insert Log entry.
Entry Id = 0

Exception details:
System.InvalidOperationException occurred
  HResult=0x80131509
  Message=The property 'Id' is part of the object's key information and cannot be modified. 
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Data.Entity.Core.Objects.EntityEntry.VerifyEntityValueIsEditable(StateManagerTypeMetadata typeMetadata, Int32 ordinal, String memberName)
   at System.Data.Entity.Core.Objects.EntityEntry.GetAndValidateChangeMemberInfo(String entityMemberName, Object complexObject, String complexObjectMemberName, StateManagerTypeMetadata& typeMetadata, String& changingMemberName, Object& changingObject)
   at System.Data.Entity.Core.Objects.EntityEntry.EntityMemberChanging(String entityMemberName, Object complexObject, String complexObjectMemberName)
   at System.Data.Entity.Core.Objects.EntityEntry.EntityMemberChanging(String entityMemberName)
   at System.Data.Entity.Core.Objects.ObjectStateEntry.System.Data.Entity.Core.Objects.DataClasses.IEntityChangeTracker.EntityMemberChanging(String entityMemberName)
   at System.Data.Entity.Core.Objects.Internal.SnapshotChangeTrackingStrategy.SetCurrentValue(EntityEntry entry, StateManagerMemberMetadata member, Int32 ordinal, Object target, Object value)
   at System.Data.Entity.Core.Objects.Internal.EntityWrapper`1.SetCurrentValue(EntityEntry entry, StateManagerMemberMetadata member, Int32 ordinal, Object target, Object value)
   at System.Data.Entity.Core.Objects.EntityEntry.SetCurrentEntityValue(StateManagerTypeMetadata metadata, Int32 ordinal, Object userObject, Object newValue)
   at System.Data.Entity.Core.Objects.ObjectStateEntryDbUpdatableDataRecord.SetRecordValue(Int32 ordinal, Object value)
   at System.Data.Entity.Core.Mapping.Update.Internal.PropagatorResult.SetServerGenValue(Object value)
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.BackPropagateServerGen(List`1 generatedValues)
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   at System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)
   at System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction)
   at System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update()
   at System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__35()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   at System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass2a.<SaveChangesInternal>b__27()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   at System.Data.Entity.DbContext.SaveChanges()
   at Nop.Data.EfRepository`1.Insert(T entity) in C:\Projects\NopCommerce4.0\nopCommerce\src\Libraries\Nop.Data\EfRepository.cs:line 103
   at Nop.Services.Logging.DefaultLogger.InsertLog(LogLevel logLevel, String shortMessage, String fullMessage, Customer customer) in C:\Projects\NopCommerce4.0\nopCommerce\src\Libraries\Nop.Services\Logging\DefaultLogger.cs:line 236
   at Nop.Services.Logging.LoggingExtensions.FilteredLog(ILogger logger, LogLevel level, String message, Exception exception, Customer customer) in C:\Projects\NopCommerce4.0\nopCommerce\src\Libraries\Nop.Services\Logging\LoggingExtensions.cs:line 89
   at Nop.Services.Logging.LoggingExtensions.Error(ILogger logger, String message, Exception exception, Customer customer) in C:\Projects\NopCommerce4.0\nopCommerce\src\Libraries\Nop.Services\Logging\LoggingExtensions.cs:line 57
   at Nop.Services.Tasks.TaskThread.Run() in C:\Projects\NopCommerce4.0\nopCommerce\src\Libraries\Nop.Services\Tasks\TaskThread.cs:line 71
   at Nop.Services.Tasks.TaskThread.TimerHandler(Object state) in C:\Projects\NopCommerce4.0\nopCommerce\src\Libraries\Nop.Services\Tasks\TaskThread.cs:line 81
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireQueuedTimerCompletion(Object state)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by ArturAlekseev** [comment]
I was not able to find out why it is happening. Mostly this code works as expected. But sometimes exception occurs. And Id is not always 0. Sometimes > 0. Maybe its some sort of EF bug.

**Comment by dev-siberia** [comment]
Hey. Now I solved such a problem. It is associated with ScheduleTask. You need to specify the correct url Store in the settings or database. I previously specified the wrong port, since I deployed the backup copy.
You can find error logs in the database.

**Comment by ArturAlekseev** [comment]
Well ofcourse I'v found where it happens. It happens for me when I debug. So my url is localhost:port.
And the issue is that it should log error about wrong url without making any exception that says there is a problem inserting error log record.

**Comment by dev-siberia** [comment]
> But some times later exception...
In my case, the error was registered in the database in the Log table. Are there records there?

**Comment by AndreiMaz** [comment]
Never experienced this issue and not sure how to reproduce it

**Comment by ArturAlekseev** [comment]
Synced with latest commits and don't experience it anymore.

**Comment by ptr1120** [comment]
We also experience this issue very often (NopCommerce version 4.0):
```
System.InvalidOperationException: The property 'Id' is pa
rt of the object's key information and cannot be modified.
bei System.Data.Entity.Core.Objects.EntityEntry.VerifyEntityValueIsEditable(S
tateManagerTypeMetadata typeMetadata, Int32 ordinal, String memberName)
bei System.Data.Entity.Core.Objects.EntityEntry.GetAndValidateChangeMemberInf
o(String entityMemberName, Object complexObject, String complexObjectMemberName,
StateManagerTypeMetadata& typeMetadata, String& changingMemberName, Object& cha
ngingObject)
bei System.Data.Entity.Core.Objects.EntityEntry.EntityMemberChanging(String e
ntityMemberName, Object complexObject, String complexObjectMemberName)
bei System.Data.Entity.Core.Objects.Internal.SnapshotChangeTrackingStrategy.S
etCurrentValue(EntityEntry entry, StateManagerMemberMetadata member, Int32 ordin
al, Object target, Object value)
bei System.Data.Entity.Core.Objects.EntityEntry.SetCurrentEntityValue(StateMa
nagerTypeMetadata metadata, Int32 ordinal, Object userObject, Object newValue)
bei System.Data.Entity.Core.Objects.ObjectStateEntryDbUpdatableDataRecord.Set
RecordValue(Int32 ordinal, Object value)
bei System.Data.Entity.Core.Mapping.Update.Internal.PropagatorResult.SetServe
rGenValue(Object value)
bei System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.BackProp
agateServerGen(List`1 generatedValues)
bei System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
bei System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Fun
c`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction,
Boolean releaseConnectionOnSuccess)
bei System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOpti
ons options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransacti
on)
bei System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult]
(Func`1 operation)
bei System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOpt
ions options, Boolean executeInExistingTransaction)
bei System.Data.Entity.Internal.InternalContext.SaveChanges()
bei Nop.Data.EfRepository`1.Insert(T entity)
bei Nop.Services.Logging.DefaultLogger.InsertLog(LogLevel logLevel, String sh
ortMessage, String fullMessage, Customer customer)
```

This is very problematic since nopCommerce instance really crashes with this exception.
I suspect this issue occurs especcially when the Store Url is not correctly stored in Database (e.g. wrong port). Then the KeepAllive Task produces a lot of timeout exceptions which are logged to the database.

Best regards,
Peter

**Comment by ArturAlekseev** [comment]
Just update entityframework or sync with latest commits.
