### ISSUE TITLE
Issue with Upload plugin or theme on Azure Web App

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/nopCommerce#2855]
Source: https://www.nopcommerce.com/boards/t/50613/issue-with-upload-plugin-or-theme-on-azure-web-app.aspx

**Comment by dahlbyk** [comment]
Possibly related: I'm periodically getting plugin-related errors like this on an Azure-deployed app:

#### Access is denied
<details>
<summary>Application startup exception: System.Exception: Plugin 'Manual Payment'. Access to the path 'D:\home\site\wwwroot\Plugins\bin\Nop.Plugin.Payments.Manual.dll' is denied.</summary>

```
Application startup exception: System.Exception: Plugin 'Manual Payment'. Access to the path 'D:\home\site\wwwroot\Plugins\bin\Nop.Plugin.Payments.Manual.dll' is denied.
Access to the path 'D:\home\site\wwwroot\Plugins\bin\Nop.Plugin.Payments.Manual.dll' is denied.
 ---> System.Exception: Plugin 'Manual Payment'. Access to the path 'D:\home\site\wwwroot\Plugins\bin\Nop.Plugin.Payments.Manual.dll' is denied. ---> System.UnauthorizedAccessException: Access to the path 'D:\home\site\wwwroot\Plugins\bin\Nop.Plugin.Payments.Manual.dll' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Nop.Core.Plugins.PluginManager.ShadowCopyFile(FileInfo plug, DirectoryInfo shadowCopyPlugFolder)
   at Nop.Core.Plugins.PluginManager.PerformFileDeploy(FileInfo plug, ApplicationPartManager applicationPartManager, NopConfig config)
   at Nop.Core.Plugins.PluginManager.Initialize(ApplicationPartManager applicationPartManager, NopConfig config)
   --- End of inner exception stack trace ---
   at Nop.Core.Plugins.PluginManager.Initialize(ApplicationPartManager applicationPartManager, NopConfig config)
   --- End of inner exception stack trace ---
   at Nop.Core.Plugins.PluginManager.Initialize(ApplicationPartManager applicationPartManager, NopConfig config)
   at Nop.Core.Infrastructure.NopEngine.Initialize(IServiceCollection services)
   at Nop.Web.Framework.Infrastructure.Extensions.ServiceCollectionExtensions.ConfigureApplicationServices(IServiceCollection services, IConfigurationRoot configuration)
   at Nop.Web.Startup.ConfigureServices(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```

</details>

#### Being used by another process

<details>
<summary>Application startup exception: System.Exception: Plugin 'Must be assigned to customer role'. Could not load file or assembly 'Nop.Plugin.DiscountRules.CustomerRoles.dll' or one of its dependencies. The process cannot access the file because it is being used by another process. (Exception from HRESULT: 0x80070020)</summary>

```
Application startup exception: System.Exception: Plugin 'Must be assigned to customer role'. Could not load file or assembly 'Nop.Plugin.DiscountRules.CustomerRoles.dll' or one of its dependencies. The process cannot access the file because it is being used by another process. (Exception from HRESULT: 0x80070020)
Could not load file or assembly 'Nop.Plugin.DiscountRules.CustomerRoles.dll' or one of its dependencies. The process cannot access the file because it is being used by another process. (Exception from HRESULT: 0x80070020)
The process cannot access the file because it is being used by another process. (Exception from HRESULT: 0x80070020)
 ---> System.Exception: Plugin 'Must be assigned to customer role'. Could not load file or assembly 'Nop.Plugin.DiscountRules.CustomerRoles.dll' or one of its dependencies. The process cannot access the file because it is being used by another process. (Exception from HRESULT: 0x80070020) ---> System.IO.FileLoadException: Could not load file or assembly 'Nop.Plugin.DiscountRules.CustomerRoles.dll' or one of its dependencies. The process cannot access the file because it is being used by another process. (Exception from HRESULT: 0x80070020) ---> System.IO.FileLoadException: The process cannot access the file because it is being used by another process. (Exception from HRESULT: 0x80070020)
   --- End of inner exception stack trace ---
   at System.Reflection.AssemblyName.nGetFileInformation(String s)
   at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
   at Nop.Core.Plugins.PluginManager.PerformFileDeploy(FileInfo plug, ApplicationPartManager applicationPartManager, NopConfig config) in D:\home\site\repository\src\Libraries\Nop.Core\Plugins\PluginManager.cs:line 201
   at Nop.Core.Plugins.PluginManager.Initialize(ApplicationPartManager applicationPartManager, NopConfig config) in D:\home\site\repository\src\Libraries\Nop.Core\Plugins\PluginManager.cs:line 417
   --- End of inner exception stack trace ---
   at Nop.Core.Plugins.PluginManager.Initialize(ApplicationPartManager applicationPartManager, NopConfig config) in D:\home\site\repository\src\Libraries\Nop.Core\Plugins\PluginManager.cs:line 453
   --- End of inner exception stack trace ---
   at Nop.Core.Plugins.PluginManager.Initialize(ApplicationPartManager applicationPartManager, NopConfig config) in D:\home\site\repository\src\Libraries\Nop.Core\Plugins\PluginManager.cs:line 464
   at Nop.Core.Infrastructure.NopEngine.Initialize(IServiceCollection services) in D:\home\site\repository\src\Libraries\Nop.Core\Infrastructure\NopEngine.cs:line 154
   at Nop.Web.Framework.Infrastructure.Extensions.ServiceCollectionExtensions.ConfigureApplicationServices(IServiceCollection services, IConfigurationRoot configuration) in D:\home\site\repository\src\Presentation\Nop.Web.Framework\Infrastructure\Extensions\ServiceCollectionExtensions.cs:line 49
   at Nop.Web.Startup.ConfigureServices(IServiceCollection services) in D:\home\site\repository\src\Presentation\Nop.Web\Startup.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```

</details>

**Comment by dahlbyk** [comment]
Just hit another variation today. This always occurs on an otherwise healthy deploy, apparently when the app pool resets (seemingly at random). With continuous monitoring, I just hit a failure today after 11 days of consistent uptime.

#### Access is denied

<details>
<summary>Application startup exception: System.Exception: Plugin 'Credit Card'. Could not load file or assembly 'Nop.Plugin.Payments.Manual.dll' or one of its dependencies. Access is denied.
Could not load file or assembly 'Nop.Plugin.Payments.Manual.dll' or one of its dependencies. Access is denied.</summary>

```
Application startup exception: System.Exception: Plugin 'Credit Card'. Could not load file or assembly 'Nop.Plugin.Payments.Manual.dll' or one of its dependencies. Access is denied.
Could not load file or assembly 'Nop.Plugin.Payments.Manual.dll' or one of its dependencies. Access is denied.
Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
 ---> System.Exception: Plugin 'Credit Card'. Could not load file or assembly 'Nop.Plugin.Payments.Manual.dll' or one of its dependencies. Access is denied. ---> System.IO.FileLoadException: Could not load file or assembly 'Nop.Plugin.Payments.Manual.dll' or one of its dependencies. Access is denied. ---> System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   --- End of inner exception stack trace ---
   at System.Reflection.AssemblyName.nGetFileInformation(String s)
   at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
   at Nop.Core.Plugins.PluginManager.PerformFileDeploy(FileInfo plug, ApplicationPartManager applicationPartManager, NopConfig config)
   at Nop.Core.Plugins.PluginManager.Initialize(ApplicationPartManager applicationPartManager, NopConfig config)
   --- End of inner exception stack trace ---
   at Nop.Core.Plugins.PluginManager.Initialize(ApplicationPartManager applicationPartManager, NopConfig config)
   --- End of inner exception stack trace ---
   at Nop.Core.Plugins.PluginManager.Initialize(ApplicationPartManager applicationPartManager, NopConfig config)
   at Nop.Core.Infrastructure.NopEngine.Initialize(IServiceCollection services)
   at Nop.Web.Framework.Infrastructure.Extensions.ServiceCollectionExtensions.ConfigureApplicationServices(IServiceCollection services, IConfigurationRoot configuration)
   at Nop.Web.Startup.ConfigureServices(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```
</details>

**Comment by dahlbyk** [comment]
I just found https://blogs.msdn.microsoft.com/waws/2017/08/02/asp-net-and-asp-net-core-application-restarts-on-azure-app-service/. Going to try setting `WEBSITE_DYNAMIC_CACHE = 0`.

(My app is in production now, and I just hit my first actual downtime due to this. Any update/guidance would be appreciated!)

**Comment by skoshelev** [comment]
Closed #2855

**Comment by skoshelev** [comment]
@dahlbyk 
Yes, please create all your issue one by one in separate tickets

**Comment by dahlbyk** [comment]
Looks like I was encountering https://github.com/nopSolutions/nopCommerce/issues/2795. I will try be6ad5f5af125478a2a0a49afdcfef28eaf7ee6f.
