### ISSUE TITLE
An item with the same key has already been added

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#2917]
nopCommerce version: 4.00

When importing the product , show this error.
This is system log:
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Nop.Services.ExportImport.ImportManager.ImportProductsFromXlsx(Stream stream)
   at Nop.Web.Areas.Admin.Controllers.ProductController.ImportExcel(IFormFile importexcelfile)

**Comment by tigran-avdalyan** [comment]
i Fix the problem, but its a real problem
History
i have multistore (Electronics, Stationary and Food)


in Electronics store i have category by name Notebook(computer)
in Stationary store i have category by name Notebook(copybook)
and i want to import products to Food store, and show error
(all Categories have Limitation by Store, first Notebook for Electronics store, second for Stationary store)
then i reneme Notebook(computer) to Laptop, and import products .

**Comment by AxelAndersen** [comment]
Is this something that some one is working on in version 4.0?

**Comment by skoshelev** [comment]
Also see this work item: https://github.com/nopSolutions/nopCommerce/issues/2918

**Comment by skoshelev** [comment]
@tigran-avdalyan I fixed this problem, but you have to be careful, nopcommerce isn't support store mapping on export/import functions. See #2918 issue.

**Comment by skoshelev** [comment]
Closed #2917
