### ISSUE TITLE
4.1 dev branch does not run on azure web apps

### ISSUE THREAD

**Issue by lintho** [nopSolutions/nopCommerce#3098]
nopCommerce version: 4.1(dev branch)

Steps to reproduce the problem: 
Publish dev branch to azure web app.
Install db etc.
Recive error from .netcore saying:
(HTTP Error 502.5 - Process Failure) 

The web app itself has the extension "ASP.NET Core Extensions Version 2.1.0-preview2-final" installed as well. But does not work anyway. All other dotnet core 2.0, and 2.1 works fine, but nopcommerce does not.

**Comment by lintho** [comment]
Contact me if you need testing etc.

**Comment by lintho** [comment]
Log from stdout

Unhandled Exception: Unhandled Exception: : Microsoft.EntityFrameworkCore.Update[10000]
      An exception occurred in the database while saving changes for context type 'Nop.Data.NopObjectContext'.
      System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
         at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllCSystem.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at Nop.Data.EfRepository`1.Insert(TEntity entity) in D:\home\site\repository\src\Libraries\Nop.Data\EfRepository.cs:line 81
   at Nop.Services.Logging.DefaultLogger.InsertLog(LogLevel logLevel, String shortMessage, String fullMessage, Customer customer) in D:\home\site\repository\src\Libraries\Nop.Services\Logging\DefaultLogger.cs:line 228
   at Nop.Custom.Services.Logging.CustomLogger.InsertLog(LogLevel logLevel, String shortMessage, String fullMessage, Customer customer) in D:\home\site\repository\src\Custom\Nop.Custom.Services\Logging\CustomLogger.cs:line 36
   at Nop.Services.Logging.LoggingExtensions.FilteredLog(ILogger logger, LogLevel level, String message, Exception exception, Customer customer) in D:\home\site\repository\src\Libraries\Nop.Services\Logging\LoggingExtensions.cs:line 89
   at Nop.Services.Logging.LoggingExtensions.Error(ILogger logger, String message, Exception exception, Customer customer) in D:\home\site\repository\src\Libraries\Nop.Services\Logging\LoggingExtensions.cs:line 57
   at Nop.Services.Tasks.TaskThread.Run() in D:\home\site\repository\src\Libraries\Nop.Services\Tasks\TaskThread.cs:line 69
   at Nop.Services.Tasks.TaskThread.TimerHandler(Object state) in D:\home\site\repository\src\Libraries\Nop.Services\Tasks\TaskThread.cs:line 79
   at System.Threading.TimerQueueTimer.<>c.<.cctor>b__22_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

**Comment by lintho** [comment]
@AndreiMaz @skoshelev  suddenly this works after doing a fetch -> merge into my project. Not sure why, but after deploying now it works. 

The same merge forced me to set up https locally, so maybe something was changed to fix this problem?
