### ISSUE TITLE
4.10 - The ntext data type cannot be selected as DISTINCT because it is not comparable

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#3111]
nopCommerce version: 4.10

Steps to reproduce the problem: 

1. Restored my Prod DB to localhost
2. Ran update query for 4.10
3. Logged into admin dashboard

Received this error:

```
System.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=The ntext data type cannot be selected as DISTINCT because it is not comparable.
  Source=Core .Net SqlClient Data Provider
  StackTrace:
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.GetResult[TResult](IEnumerable`1 valueBuffers, Boolean throwOnNullResult)
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at System.Linq.Queryable.Count[TSource](IQueryable`1 source)
   at Nop.Core.PagedList`1..ctor(IQueryable`1 source, Int32 pageIndex, Int32 pageSize, Boolean getOnlyTotalCount) in C:\Users\dootc\Documents\Visual Studio 2017\WebSites\nopCommerce_4.10_Beta_Source\Libraries\Nop.Core\PagedList.cs:line 23
   at Nop.Services.Customers.CustomerService.GetAllCustomers(Nullable`1 createdFromUtc, Nullable`1 createdToUtc, Int32 affiliateId, Int32 vendorId, Int32[] customerRoleIds, String email, String username, String firstName, String lastName, Int32 dayOfBirth, Int32 monthOfBirth, String company, String phone, String zipPostalCode, String ipAddress, Boolean loadOnlyWithShoppingCart, Nullable`1 sct, Int32 pageIndex, Int32 pageSize, Boolean getOnlyTotalCount) in C:\Users\dootc\Documents\Visual Studio 2017\WebSites\nopCommerce_4.10_Beta_Source\Libraries\Nop.Services\Customers\CustomerService.cs:line 279
   at Nop.Web.Areas.Admin.Factories.CommonModelFactory.PrepareCommonStatisticsModel() in C:\Users\dootc\Documents\Visual Studio 2017\WebSites\nopCommerce_4.10_Beta_Source\Presentation\Nop.Web\Areas\Admin\Factories\CommonModelFactory.cs:line 928
   at Nop.Web.Areas.Admin.Components.CommonStatisticsViewComponent.Invoke() in C:\Users\dootc\Documents\Visual Studio 2017\WebSites\nopCommerce_4.10_Beta_Source\Presentation\Nop.Web\Areas\Admin\Components\CommonStatistics.cs:line 56
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeSyncCore(ObjectMethodExecutor executor, ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.<InvokeAsync>d__5.MoveNext()

```

**Comment by AndreiMaz** [comment]
What database version are you using?

**Comment by Ochapparel** [comment]
SQL Server 14.0.1000

It only does it on the "Dashboard", I was able to get past the dashboard and the "Products", "Orders" etc.

**Comment by Ochapparel** [comment]
I could send you my DB if you want?

**Comment by AndreiMaz** [comment]
Is it possible for you to use SQL Server profiler and see what SQL command is generated in this case (you can set breakpoint in "GetAllCustomers" method of "CustomerService" before the executation?

**Comment by Ochapparel** [comment]
Yes, give me a few minutes, let me see what I can figure out.

**Comment by AndreiMaz** [comment]
@Ochapparel sure, it would be great. please send a link to            am [at]    nopcommerce   {dot}   com

**Comment by Ochapparel** [comment]
@AndreiMaz Sent

**Comment by Ochapparel** [comment]
I did do the Profiler (because I've never done that before) and I got the below. Hope it helps:

`exec sp_executesql N'SET NOCOUNT ON;
INSERT INTO [Log] ([CreatedOnUtc], [CustomerId], [FullMessage], [IpAddress], [LogLevelId], [PageUrl], [ReferrerUrl], [ShortMessage])
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7);
SELECT [Id]
FROM [Log]
WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();

',N'@p0 datetime2(7),@p1 int,@p2 nvarchar(max) ,@p3 nvarchar(200),@p4 int,@p5 nvarchar(4000),@p6 nvarchar(4000),@p7 nvarchar(4000)',@p0='2018-07-09 20:51:27.5720222',@p1=1,@p2=N'System.Data.SqlClient.SqlException (0x80131904): The ntext data type cannot be selected as DISTINCT because it is not comparable.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.GetResult[TResult](IEnumerable`1 valueBuffers, Boolean throwOnNullResult)
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at System.Linq.Queryable.Count[TSource](IQueryable`1 source)
   at Nop.Core.PagedList`1..ctor(IQueryable`1 source, Int32 pageIndex, Int32 pageSize, Boolean getOnlyTotalCount) in C:\Users\dootc\Documents\Visual Studio 2017\WebSites\nopCommerce_4.10_Beta_Source\Libraries\Nop.Core\PagedList.cs:line 23
   at Nop.Services.Customers.CustomerService.GetAllCustomers(Nullable`1 createdFromUtc, Nullable`1 createdToUtc, Int32 affiliateId, Int32 vendorId, Int32[] customerRoleIds, String email, String username, String firstName, String lastName, Int32 dayOfBirth, Int32 monthOfBirth, String company, String phone, String zipPostalCode, String ipAddress, Boolean loadOnlyWithShoppingCart, Nullable`1 sct, Int32 pageIndex, Int32 pageSize, Boolean getOnlyTotalCount) in C:\Users\dootc\Documents\Visual Studio 2017\WebSites\nopCommerce_4.10_Beta_Source\Libraries\Nop.Services\Customers\CustomerService.cs:line 279
   at Nop.Web.Areas.Admin.Factories.CommonModelFactory.PrepareCommonStatisticsModel() in C:\Users\dootc\Documents\Visual Studio 2017\WebSites\nopCommerce_4.10_Beta_Source\Presentation\Nop.Web\Areas\Admin\Factories\CommonModelFactory.cs:line 928
   at Nop.Web.Areas.Admin.Components.CommonStatisticsViewComponent.Invoke() in C:\Users\dootc\Documents\Visual Studio 2017\WebSites\nopCommerce_4.10_Beta_Source\Presentation\Nop.Web\Areas\Admin\Components\CommonStatistics.cs:line 56
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeSyncCore(ObjectMethodExecutor executor, ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsync(ViewComponentContext context)
   at StackExchange.Profiling.Internal.ProfilingViewComponentInvoker.InvokeAsync(ViewComponentContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore.Mvc\Internal\ProfilingViewComponentInvoker.cs:line 30
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper.InvokeCoreAsync(ViewComponentDescriptor descriptor, Object arguments)
   at AspNetCore.Areas_Admin_Views_Home_Index.ExecuteAsync() in C:\Users\dootc\Documents\Visual Studio 2017\WebSites\nopCommerce_4.10_Beta_Source\Presentation\Nop.Web\Areas\Admin\Views\Home\Index.cshtml:line 38
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 94
   at Nop.Services.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) in C:\Users\dootc\Documents\Visual Studio 2017\WebSites\nopCommerce_4.10_Beta_Source\Libraries\Nop.Services\Authentication\AuthenticationMiddleware.cs:line 76
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Nop.Core.Http.InstallUrlMiddleware.Invoke(HttpContext context, IWebHelper webHelper) in C:\Users\dootc\Documents\Visual Studio 2017\WebSites\nopCommerce_4.10_Beta_Source\Libraries\Nop.Core\Http\InstallUrlMiddleware.cs:line 51
   at Nop.Core.Http.KeepAliveMiddleware.Invoke(HttpContext context, IWebHelper webHelper) in C:\Users\dootc\Documents\Visual Studio 2017\WebSites\nopCommerce_4.10_Beta_Source\Libraries\Nop.Core\Http\KeepAliveMiddleware.cs:line 50
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
ClientConnectionId:8ad02d35-f531-4278-8a93-8201bb0d3512
Error Number:421,State:1,Class:16',@p3=N'127.0.0.1',@p4=40,@p5=N'http://localhost:15536/admin',@p6=NULL,@p7=N'The ntext data type cannot be selected as DISTINCT because it is not comparable.'`

**Comment by DmitriyKulagin** [comment]
@Ochapparel 

SQL Server's [ntext](https://docs.microsoft.com/en-us/sql/t-sql/data-types/ntext-text-and-image-transact-sql?view=sql-server-2017) datatypes are obsolete. 

> IMPORTANT! ntext, text, and image data types will be removed in a future version of SQL Server. Avoid using these data types in new development work, and plan to modify applications that currently use them. Use nvarchar(max), varchar(max), and varbinary(max) instead.

I tried to apply the script to your database and it all worked for me. Do yourself the same thing and the problem will be solved. Let me know if there are any difficulties.

`ALTER TABLE [ochappareldb_localhost_410_beta].[dbo].[Customer] ALTER COLUMN [AdminComment] NVARCHAR(max);`

**Comment by AndreiMaz** [comment]
@Ochapparel by the way, why is it ntext in your case if nopCommerce sets as "nvarchar(max)" by default?

**Comment by Ochapparel** [comment]
@DmitriyKulagin thanks for this. That fixed me up!

@AndreiMaz Not sure where the ntext came from. I've been upgrading the DB since Nop 1.9...maybe something old?
