### ISSUE TITLE
4.10 BETA - Error after publish to IIS 10

### ISSUE THREAD

**Issue by alecrt** [nopSolutions/nopCommerce#3135]
After manually publishing nop to a win 2016 server environment i get the following error:

```
fail: Microsoft.EntityFrameworkCore.Update[10000]
      An exception occurred in the database while saving changes for context type 'Nop.Data.NopObjectContext'.
      System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
         at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
fail: Microsoft.EntityFrameworkCore.Update[10000]
      An exception occurred in the database while saving changes for context type 'Nop.Data.NopObjectContext'.
      System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
         at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
fail: Microsoft.EntityFrameworkCore.Update[10000]
      An exception occurred in the database while saving changes for context type 'Nop.Data.NopObjectContext'.
      System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
         at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
```

**Comment by alecrt** [comment]
Closing, there was a problem with the connection string.

**Comment by alecrt** [comment]
I still get this error random. Maybe i leave it open if you want to double check it.

**Comment by amiradib** [comment]
i get this error & can't find any solution
my connection string is Ok
it was be ok but i suddenly get this error


fail: Microsoft.EntityFrameworkCore.Update[10000]
      An exception occurred in the database while saving changes for context typ
e 'Nop.Data.NopObjectContext'.
      System.InvalidOperationException: A second operation started on this conte
xt before a previous operation completed. Any instance members are not guarantee
d to be thread safe.
         at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCrit
icalSection()
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.S
aveChanges(IReadOnlyList`1 entriesToSave)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.S
aveChanges(Boolean acceptAllChangesOnSuccess)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAl
lChangesOnSuccess)
System.InvalidOperationException: A second operation started on this context bef
ore a previous operation completed. Any instance members are not guaranteed to b
e thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSe
ction()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveCha
nges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveCha
nges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChang
esOnSuccess)

Unhandled Exception:
Unhandled Exception: fail: Microsoft.EntityFrameworkCore.Update[10000]
      An exception occurred in the database while saving changes for context typ
e 'Nop.Data.NopObjectContext'.
      System.InvalidOperationException: A second operation started on this conte
xt before a previous operation completed. Any instance members are not guarantee
d to be thread safe.
         at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCrit
icalSection()
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.S
aveChanges(IReadOnlyList`1 entriesToSave)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.S
aveChanges(Boolean acceptAllChangesOnSuccess)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAl
lChangesOnSuccess)
System.InvalidOperationException: A second operation started on this context bef
ore a previous operation completed. Any instance members are not guaranteed to b
e thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSe
ction()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveCha
nges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveCha
nges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChang
esOnSuccess)
System.InvalidOperationException: A second operation started on this context bef
ore a previous operation completed. Any instance members are not guaranteed to b
e thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSe
ction()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveCha
nges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveCha
nges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChang
esOnSuccess)
   at Nop.Data.EfRepository`1.Insert(TEntity entity)
   at Nop.Services.Logging.DefaultLogger.InsertLog(LogLevel logLevel, String sho
rtMessage, String fullMessage, Customer customer)
   at Nop.Services.Logging.DefaultLogger.Error(String message, Exception excepti
on, Customer customer)
   at Nop.Services.Tasks.TaskThread.Run()
   at Nop.Services.Tasks.TaskThread.TimerHandler(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()System.InvalidOperationExcepti
on: A second operation started on this context before a previous operation compl
eted. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSe
ction()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveCha
nges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveCha
nges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChang
esOnSuccess)
   at Nop.Data.EfRepository`1.Insert(TEntity entity)
   at Nop.Services.Logging.DefaultLogger.InsertLog(LogLevel logLevel, String sho
rtMessage, String fullMessage, Customer customer)
   at Nop.Services.Logging.DefaultLogger.Error(String message, Exception excepti
on, Customer customer)
   at Nop.Services.Tasks.TaskThread.Run()
   at Nop.Services.Tasks.TaskThread.TimerHandler(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (440ms) [Parameters=[@p0='?' (DbType = DateTime2), @p1=
'?' (DbType = Int32), @p2='?' (Size = 4000), @p3='?' (Size = 200), @p4='?' (DbTy
pe = Int32), @p5='?' (Size = 4000), @p6='?' (Size = 4000), @p7='?' (Size = 4000)
], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [Log] ([CreatedOnUtc], [CustomerId], [FullMessage], [IpAddress
], [LogLevelId], [PageUrl], [ReferrerUrl], [ShortMessage])
      VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7);
      SELECT [Id]
      FROM [Log]
      WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();

**Comment by alecrt** [comment]
@amiradib 
commit 6470d22b4a43b82b71171604ea4de28b389b41a2 should have fixed this issue

**Comment by amiradib** [comment]
Thanks a lot
