### ISSUE TITLE
4.10 BETA - Error on run on Ubuntu 16.04

### ISSUE THREAD

**Issue by VR-Architect** [nopSolutions/nopCommerce#3144]
nopCommerce version: 4.10 Beta

Steps to reproduce the problem: 

- Build for Release on VS2017
- Publish to a new folder
- FTP folder over to my Ubuntu 16.04 server running .NET Core 2.1.3
- Run the nopCommerce application (sudo dotnet /var/www/nopCommerce/Nop.Web.dll)

```
Error:
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at System.IO.Path.GetFullPath(String path)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.CreateFileWatcher(String root, ExclusionFilters filters)
   at Nop.Core.Infrastructure.NopFileProvider..ctor(IHostingEnvironment hostingEnvironment) in C:\_Source\Libraries\Nop.Core\Infrastructure\NopFileProvider.cs:line 23
   at Nop.Core.Infrastructure.NopEngine.Initialize(IServiceCollection services) in C:\_Source\Libraries\Nop.Core\Infrastructure\NopEngine.cs:line 150
   at Nop.Web.Framework.Infrastructure.Extensions.ServiceCollectionExtensions.ConfigureApplicationServices(IServiceCollection services, IConfiguration configuration) in C:\_Source\Presentation\Nop.Web.Framework\Infrastructure\Extensions\ServiceCollectionExtensions.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Nop.Web.Program.Main(String[] args) in C:\_Source\Presentation\Nop.Web\Program.cs:line 10
./publish: line 9: 24953 Aborted                 (core dumped) 
```

**Comment by AndreiMaz** [comment]
duplicated https://github.com/nopSolutions/nopCommerce/issues/3095
