### ISSUE TITLE
Printing Invoices from Localhost

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#3147]
nopCommerce version: 4.10 Beta

Steps to reproduce the problem: 

1. Go into Admin -> Order -> Check mark an order
2. Click "Print PDF invoices (selected)"

I get:

```
System.UnauthorizedAccessException: Access to the path 'C:\' is denied.
   at Nop.Web.Framework.Infrastructure.Extensions.ApplicationBuilderExtensions.<>c.<UseNopExceptionHandler>b__1_1(HttpContext context) in C:\Users\dootc\Documents\Visual Studio 2017\WebSites\nopCommerce_4.10_Beta_Source\Presentation\Nop.Web.Framework\Infrastructure\Extensions\ApplicationBuilderExtensions.cs:line 76
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

I believe it's when trying to add the "logo". I was able to do this in 4.00.

**Comment by rajupaladiya** [comment]
This seems file/folder permission issue.

**Comment by Ochapparel** [comment]
@rajupaladiya I would agree, but it works fine with 4.00 and I haven't changed anything. Just figured I'd report it :)

**Comment by RuS984** [comment]
Make sure you have rights to save into a folder where you want to save it in.

#3147 Closed
