### ISSUE TITLE
4.10 run witout debug error on macos

### ISSUE THREAD

**Issue by sargin48** [nopSolutions/nopCommerce#3196]
nopCommerce version: 4.10

Steps to reproduce the problem: 

Unhandled Exception: System.Exception: Plugin 'Must be assigned to customer role'. Could not load file or assembly '/Users/abdullahsargin/Projects/nopCommerce_4.10/Presentation/Nop.Web/Plugins\bin/Nop.Plugin.DiscountRules.CustomerRoles.dll'. The system cannot find the file specified.

Could not load file or assembly '/Users/abdullahsargin/Projects/nopCommerce_4.10/Presentation/Nop.Web/Plugins\bin/Nop.Plugin.DiscountRules.CustomerRoles.dll'. The system cannot find the file specified.

 ---> System.Exception: Plugin 'Must be assigned to customer role'. Could not load file or assembly '/Users/abdullahsargin/Projects/nopCommerce_4.10/Presentation/Nop.Web/Plugins\bin/Nop.Plugin.DiscountRules.CustomerRoles.dll'. The system cannot find the file specified.
 ---> System.IO.FileNotFoundException: Could not load file or assembly '/Users/abdullahsargin/Projects/nopCommerce_4.10/Presentation/Nop.Web/Plugins\bin/Nop.Plugin.DiscountRules.CustomerRoles.dll'. The system cannot find the file specified.

   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Nop.Core.Plugins.PluginManager.RegisterPluginDefinition(NopConfig config, ApplicationPartManager applicationPartManager, String plug) in /Users/abdullahsargin/Projects/nopCommerce_4.10/Libraries/Nop.Core/Plugins/PluginManager.cs:line 244
   at Nop.Core.Plugins.PluginManager.PerformFileDeploy(String plug, ApplicationPartManager applicationPartManager, NopConfig config, String shadowCopyPath) in /Users/abdullahsargin/Projects/nopCommerce_4.10/Libraries/Nop.Core/Plugins/PluginManager.cs:line 220
   at Nop.Core.Plugins.PluginManager.Initialize(ApplicationPartManager applicationPartManager, NopConfig config) in /Users/abdullahsargin/Projects/nopCommerce_4.10/Libraries/Nop.Core/Plugins/PluginManager.cs:line 479
   --- End of inner exception stack trace ---
   at Nop.Core.Plugins.PluginManager.Initialize(ApplicationPartManager applicationPartManager, NopConfig config) in /Users/abdullahsargin/Projects/nopCommerce_4.10/Libraries/Nop.Core/Plugins/PluginManager.cs:line 515
   --- End of inner exception stack trace ---
   at Nop.Core.Plugins.PluginManager.Initialize(ApplicationPartManager applicationPartManager, NopConfig config) in /Users/abdullahsargin/Projects/nopCommerce_4.10/Libraries/Nop.Core/Plugins/PluginManager.cs:line 526
   at Nop.Core.Infrastructure.NopEngine.Initialize(IServiceCollection services) in /Users/abdullahsargin/Projects/nopCommerce_4.10/Libraries/Nop.Core/Infrastructure/NopEngine.cs:line 155
   at Nop.Web.Framework.Infrastructure.Extensions.ServiceCollectionExtensions.ConfigureApplicationServices(IServiceCollection services, IConfiguration configuration) in /Users/abdullahsargin/Projects/nopCommerce_4.10/Presentation/Nop.Web.Framework/Infrastructure/Extensions/ServiceCollectionExtensions.cs:line 57
   at Nop.Web.Startup.ConfigureServices(IServiceCollection services) in /Users/abdullahsargin/Projects/nopCommerce_4.10/Presentation/Nop.Web/Startup.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Nop.Web.Program.Main(String[] args) in /Users/abdullahsargin/Projects/nopCommerce_4.10/Presentation/Nop.Web/Program.cs:line 10

**Comment by AndreiMaz** [comment]
MacOS is not supported yet
