### ISSUE TITLE
File path issue in mac

### ISSUE THREAD

**Issue by alirezakhosravi** [nopSolutions/nopCommerce#3348]
nopCommerce version:  4.1
I am using nopCommerce version 4.1 on mac os with visual studio for mac, when I run this solution, I get error on creating path.

```
            Plugin 'Must be assigned to customer role'. Could not load file or assembly '/Users/alireza/Desktop/NopCommerce/Presentation/Nop.Web/Plugins\\bin/Nop.Plugin.DiscountRules.CustomerRoles.dll'. The system cannot find the file specified.\n\nCould not load file or assembly '/Users/alireza/Desktop/NopCommerce/Presentation/Nop.Web/Plugins\\bin/Nop.Plugin.DiscountRules.CustomerRoles.dll'. The system cannot find the file specified.\n\n
```

I changed the MapPath function in NopFileProvider class to
```
path = Environment.OSVersion.Platform == PlatformID.Win32NT
                ? path.Replace("~/", string.Empty).TrimStart('/').Replace('/', '\\')
                : path.Replace("~/", string.Empty).TrimStart('/');
```
and my problem is resolved.

**Comment by Joebeazelman** [comment]
Following up from Stackoverflow.  He claimed he has a working build on MacOS. Not sure if this was the only modification, but it's the firsr error encountered after running the build.  I can try a do a build on my Mac with this change and do some light user testing.  If it works, it is worthy of an experimental branch.  A ton of developers want to do their development on a Mac and even more want to deploy it on Unix OSes.

**Comment by mwoffenden** [comment]
What's the current status of 4.1 development on VisualStudio for MacOS?  Is it functional with the above mentioned fix?

**Comment by lintho** [comment]
@Joebeazelman  Did u manage to run nopcommerce on mac?

**Comment by lintho** [comment]
We made 4.1 run on MAC doing the following:

Edited the path below to (NopFileProvider line 438) to:

```
public virtual string MapPath(string path)
{
      path = path.Replace("~/", string.Empty).TrimStart('/');   //.Replace('/', '\\');
      return Path.Combine(BaseDirectory ?? string.Empty, path);
}
```

and in project src/Build/ClearPluginAssemblies.proj we removed the following:

`<Exec Command='dotnet "$(MSBuildProjectDirectory)\ClearPluginAssemblies.dll" "OutputPath=$(OutputPath)|PluginPath=$(PluginPath)|SaveLocalesFolders=$(SaveLocalesFolders)"' />`

**Comment by mwoffenden** [comment]
We got it to run.  However the installer (with remote SQL Server database) failed.  Ideas?
`System.PlatformNotSupportedException: Windows Principal functionality is not supported on this platform.
   at Nop.Web.Framework.Infrastructure.Extensions.ApplicationBuilderExtensions.<>c.<UseNopExceptionHandler>b__1_1(HttpContext context) in /Users/Michael/Dropbox/IRC/R & D/NOPCOMMERCE/4.10/SOURCE/Presentation/Nop.Web.Framework/Infrastructure/Extensions/ApplicationBuilderExtensions.cs:line 83
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

**Comment by skoshelev** [comment]
Hi all. We have an other [ticket](https://github.com/nopSolutions/nopCommerce/issues/3095), I think it fix all problems in MAC to. Also see this [branch](https://github.com/nopSolutions/nopCommerce/commits/issue-3095-Run-nopCommerce-on-Linux), we fixed meny problrms with work on UNIX system.

**Comment by cleopatra27** [comment]
> We got it to run. However the installer (with remote SQL Server database) failed. Ideas?
> 
> `System.PlatformNotSupportedException: Windows Principal functionality is not supported on this platform. at Nop.Web.Framework.Infrastructure.Extensions.ApplicationBuilderExtensions.<>c.<UseNopExceptionHandler>b__1_1(HttpContext context) in ...4.10/SOURCE/Presentation/Nop.Web.Framework/Infrastructure/Extensions/ApplicationBuilderExtensions.cs:line 83 at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

hi.... did you get this to work?

**Comment by mwoffenden** [comment]
We gave up for now and are waiting for the official fully working Mac development release.
