### ISSUE TITLE
Official Feed Manager OperationCanceledException

### ISSUE THREAD

**Issue by ayberkcal** [nopSolutions/nopCommerce#3494]
nopCommerce version: 4.10

Steps to reproduce the problem: 
In production server when I enter Plugin List pages throw exception and display "We're sorry, an internal error occurred." exception. It does not occuer in local machine.

Log:
```
System.OperationCanceledException: The operation was canceled.
   at System.Net.HttpWebRequest.GetResponse()
   at Nop.Core.Plugins.OfficialFeedManager.GetDocument(String feedQuery, Object[] args) in C:\development\NopCommerce\src\Libraries\Nop.Core\Plugins\OfficialFeedManager.cs:line 25
   at Nop.Core.Plugins.OfficialFeedManager.GetVersions() in C:\development\NopCommerce\src\Libraries\Nop.Core\Plugins\OfficialFeedManager.cs:line 70
   at Nop.Web.Areas.Admin.Factories.PluginModelFactory.PrepareOfficialFeedPluginSearchModel(OfficialFeedPluginSearchModel searchModel) in C:\development\NopCommerce\src\Presentation\Nop.Web\Areas\Admin\Factories\PluginModelFactory.cs:line 249
   at Nop.Web.Areas.Admin.Factories.PluginModelFactory.PreparePluginsConfigurationModel(PluginsConfigurationModel pluginsConfigurationModel) in C:\development\NopCommerce\src\Presentation\Nop.Web\Areas\Admin\Factories\PluginModelFactory.cs:line 355
   at Nop.Web.Areas.Admin.Controllers.PluginController.List() in C:\development\NopCommerce\src\Presentation\Nop.Web\Areas\Admin\Controllers\PluginController.cs:line 111
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 94
   at Nop.Services.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) in C:\development\NopCommerce\src\Libraries\Nop.Services\Authentication\AuthenticationMiddleware.cs:line 79
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Nop.Core.Http.InstallUrlMiddleware.Invoke(HttpContext context, IWebHelper webHelper) in C:\development\NopCommerce\src\Libraries\Nop.Core\Http\InstallUrlMiddleware.cs:line 51
   at Nop.Core.Http.KeepAliveMiddleware.Invoke(HttpContext context, IWebHelper webHelper) in C:\development\NopCommerce\src\Libraries\Nop.Core\Http\KeepAliveMiddleware.cs:line 50
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
```

**Comment by RomanovM** [comment]
Already fixed. See https://github.com/nopSolutions/nopCommerce/issues/3182
