### ISSUE TITLE
 Could not find a part of the path

### ISSUE THREAD

**Issue by duweiblog** [nopSolutions/nopCommerce#3507]
Ubuntu deploy Success,access “localhost:80/install" ,The following error occurred:

fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/nop/App_Data\Localization\Installation\'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Nop.Web.Infrastructure.Installation.InstallationLocalizationService.GetAvailableLanguages() in D:\project\nopCommerce-develop\nopCommerce-develop\src\Presentation\Nop.Web\Infrastructure\Installation\InstallationLocalizationService.cs:line 134
   at Nop.Web.Controllers.InstallController.Index() in D:\project\nopCommerce-develop\nopCommerce-develop\src\Presentation\Nop.Web\Controllers\InstallController.cs:line 199

**Comment by duweiblog** [comment]
参考：
https://github.com/nopSolutions/nopCommerce/pull/3505/commits/9a3c57a26e885e003b4c2a6c0560ce0bcad669f4

**Comment by ayberkcal** [comment]
> 参考：
> [9a3c57a](https://github.com/nopSolutions/nopCommerce/commit/9a3c57a26e885e003b4c2a6c0560ce0bcad669f4)

I think Path.DirectorySeparatorCharacter will be more good solution.
