### ISSUE TITLE
Path Caveat with ASP.NET Core 2.2 IIS Hosting- NopFileProvider

### ISSUE THREAD

**Issue by mrafea-sa** [nopSolutions/nopCommerce#3554]
nopCommerce version: latest develop branch on Year2019 Month02 Day 21
1-from  class Program,disable-comment- the following line :
 .UseKestrel(options => options.AddServerHeader = false)
2-from command prompt  :
dotnet exec Nop.Web.dll 
The application hangs with message
Unhandled Exception: System.ArgumentException: The path must be absolute.
Parameter name: root
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Nop.Core.Infrastructure.NopFileProvider..ctor(IHostingEnvironment hostingEnvironment) in ~\Libraries\Nop.Core\Infrastructure\NopFileProvider.cs:line 23
   at Nop.Core.Infrastructure.NopEngine.Initialize(IServiceCollection services) in ~\Libraries\Nop.Core\Infrastructure\NopEngine.cs:line 148
   at Nop.Web.Framework.Infrastructure.Extensions.ServiceCollectionExtensions.ConfigureApplicationServices(IServiceCollection services, IConfiguration configuration) in ~\Presentation\Nop.Web.Framework\Infrastructure\Extensions\ServiceCollectionExtensions.cs:line 63
   at Nop.Web.Startup.ConfigureServices(IServiceCollection services) in ~\Presentation\Nop.Web\Startup.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Nop.Web.Program.Main(String[] args) in ~\Presentation\Nop.Web\Program.cs:line 10

Explanation :
Under Kestrel, Environment.CurrentDirectory points to the application root directory, while running in IIS's InProcess mode, it points to the system directory

Reference:
https://github.com/aspnet/AspNetCore/issues/4206
https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/aspnet-core-module/samples_snapshot/2.x/CurrentDirectoryHelpers.cs
https://edi.wang/post/2018/12/27/path-caveat-with-aspnet-core-22-iis-hosting

**Comment by mrafea-sa** [comment]
Dear all
i had successfully Compiled nopCommerce  and published it and it is working through iis from the published folder.
I was trying the run nopCommerce   from the development folder through "dotnet exec" . -not from the  published folder-  
Thanks.
