### ISSUE TITLE
When the setup process is complete, my site's home page is not displayed. System.Data.SqlClient.SqlException (0x80131904): 'OFFSET' 

### ISSUE THREAD

**Issue by hennychen** [nopSolutions/nopCommerce#3569]
nopCommerce version: 
**nopCommerce_4.10_Source**
Steps to reproduce the problem: 
**Follow the documentation and the installation is complete. When the setup process is complete, my site's home page is not displayed.
Direct disappear！**
Exception log：

`Nop.Web> fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[3]
Nop.Web>       An exception was thrown attempting to execute the error handler.
Nop.Web> System.Data.SqlClient.SqlException (0x80131904): 'OFFSET' �������﷨����
Nop.Web> �� FETCH �����ѡ�� NEXT ���÷���Ч��
Nop.Web>    at Nop.Web.Framework.Infrastructure.Extensions.ApplicationBuilderExtensions.<>c.<UseNopExceptionHandler>b__1_1(HttpContext context) in C:\Users\Administrator\Downloads\nopCommerce_4.10_Source\Presentation\Nop.Web.Framework\Infrastructure\Extensions\ApplicationBuilderExtensions.cs:line 83
Nop.Web>    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
Nop.Web> ClientConnectionId:eefa218a-52ee-491f-ba1d-2a1f2d520876
Nop.Web> Error Number:102,State:1,Class:15
Nop.Web> fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
Nop.Web>       An unhandled exception has occurred while executing the request.
Nop.Web> System.Data.SqlClient.SqlException (0x80131904): 'OFFSET' �������﷨����
Nop.Web> �� FETCH �����ѡ�� NEXT ���÷���Ч��
Nop.Web>    at Nop.Web.Framework.Infrastructure.Extensions.ApplicationBuilderExtensions.<>c.<UseNopExceptionHandler>b__1_1(HttpContext context) in C:\Users\Administrator\Downloads\nopCommerce_4.10_Source\Presentation\Nop.Web.Framework\Infrastructure\Extensions\ApplicationBuilderExtensions.cs:line 83
Nop.Web>    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
Nop.Web>    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
Nop.Web>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
Nop.Web> ClientConnectionId:eefa218a-52ee-491f-ba1d-2a1f2d520876
Nop.Web> Error Number:102,State:1,Class:15
Nop.Web> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
Nop.Web>       Request finished in 13809.1695ms 500 text/html; charset=utf-8
`

**Comment by hennychen** [comment]
![d2w0 hcg0fm k5mm doa5e4](https://user-images.githubusercontent.com/2526830/53636679-fe70b300-3c5b-11e9-858d-f1c8b2761ed2.png)

**Comment by hennychen** [comment]
//Enable for backwards compatibility with SQL Server 2008 and SQL Server 2008R2
    "UseRowNumberForPaging": true,

**setting true  ！**
