### ISSUE TITLE
UNC Path Error

### ISSUE THREAD

**Issue by joekrauss** [nopSolutions/nopCommerce#3824]
nopCommerce version: 4.2

Steps to reproduce the problem: 
My IIS site setup uses the following UNC path
\\192.168.1.210\webshare1\TestSite

After launching the site a new folder in the UNC path is created automatically. The new folder appears to repeat the root of the UNC path. 
\\192.168.1.210\webshare1\TestSite\192.168.1.210

Also note the new folder holds another copy of App_Data & DataProtectionKeys.

info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[58]
      Creating key {5cc54dda-ea05-45e9-88f2-0f8faecae7f7} with creation date 2019-05-09 21:50:44Z, activation date 2019-05-09 21:50:44Z, and expiration date 2019-08-07 21:50:44Z.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {5cc54dda-ea05-45e9-88f2-0f8faecae7f7} may be persisted to storage in unencrypted form.
info: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[39]
      Writing data to file '\\192.168.1.210\webshare1\TestSite\192.168.1.210\webshare1\TestSite\App_Data\DataProtectionKeys\key-5cc54dda-ea05-45e9-88f2-0f8faecae7f7.xml'.
Application startup exception: System.ArgumentException: The path must be absolute.
Parameter name: root
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Nop.Web.Framework.Infrastructure.Extensions.ApplicationBuilderExtensions.UseNopStaticFiles(IApplicationBuilder application) in C:\Users\JKRAUSS\Documents\DSGI\nopCommerce_4.20_Beta_Source\Presentation\Nop.Web.Framework\Infrastructure\Extensions\ApplicationBuilderExtensions.cs:line 197
   at Nop.Web.Framework.Infrastructure.NopCommonStartup.Configure(IApplicationBuilder application) in C:\Users\JKRAUSS\Documents\DSGI\nopCommerce_4.20_Beta_Source\Presentation\Nop.Web.Framework\Infrastructure\NopCommonStartup.cs:line 63
   at Nop.Core.Infrastructure.NopEngine.ConfigureRequestPipeline(IApplicationBuilder application) in C:\Users\JKRAUSS\Documents\DSGI\nopCommerce_4.20_Beta_Source\Libraries\Nop.Core\Infrastructure\NopEngine.cs:line 201
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception
System.ArgumentException: The path must be absolute.
Parameter name: root
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Nop.Web.Framework.Infrastructure.Extensions.ApplicationBuilderExtensions.UseNopStaticFiles(IApplicationBuilder application) in C:\Users\JKRAUSS\Documents\DSGI\nopCommerce_4.20_Beta_Source\Presentation\Nop.Web.Framework\Infrastructure\Extensions\ApplicationBuilderExtensions.cs:line 197
   at Nop.Web.Framework.Infrastructure.NopCommonStartup.Configure(IApplicationBuilder application) in C:\Users\JKRAUSS\Documents\DSGI\nopCommerce_4.20_Beta_Source\Presentation\Nop.Web.Framework\Infrastructure\NopCommonStartup.cs:line 63
   at Nop.Core.Infrastructure.NopEngine.ConfigureRequestPipeline(IApplicationBuilder application) in C:\Users\JKRAUSS\Documents\DSGI\nopCommerce_4.20_Beta_Source\Libraries\Nop.Core\Infrastructure\NopEngine.cs:line 201
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
Hosting environment: Production
Content root path: \\192.168.1.210\webshare1\TestSite
Now listening on: http://127.0.0.1:4386
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://testarms.com/  
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 141.9697ms 500 text/html; charset=utf-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://testarms.com/favicon.ico  
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.4327ms 500 text/html; charset=utf-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://127.0.0.1:4386/iisintegration  0
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.2107ms 500 text/html; charset=utf-8
Application is shutting down...

**Comment by skoshelev** [comment]
Hi @joekrauss
can you try to use the following code:
public virtual string Combine(params string[] paths)
{
	return Path.Combine(paths);
}
instead this one:
public virtual string Combine(params string[] paths)
{
	var path = Path.Combine(paths.SelectMany(p => p.Split('\\', '/')).ToArray());

	if (Environment.OSVersion.Platform == PlatformID.Unix)
		//add leading slash to correctly form path in the UNIX system
		path = "/" + path;

	return path;
}
Is it work?

**Comment by joekrauss** [comment]
Hello Sergey – The change resolved the UNC path issue based on my testing. Thanks!

**Comment by skoshelev** [comment]
Hi @joekrauss. Please try this [changes ](https://github.com/nopSolutions/nopCommerce/commit/28e9bc377069b6082240980d15a9b4740df3133a)and leave a feedback is it work good on your environment

**Comment by joekrauss** [comment]
Hello Sergey - The changes work. Thank you!

**Comment by skoshelev** [comment]
Hi @joekrauss, thank you for your help

Closed #3824
