### ISSUE TITLE
Error When Installing Multiple Plugins - There is already an open DataReader associated with this Command which must be closed first.

### ISSUE THREAD

**Issue by toddca** [nopSolutions/nopCommerce#3909]
nopCommerce version: 4.2

Steps to reproduce the problem: 
1. Go to plugins list and add a number of plugins to install, I chose like 5.
2. Restart and install plugins, and you get the following: (please note it appears one of my plugins failed to load, however the error path here is not gracefully handled)
`
InvalidOperationException: There is already an open DataReader associated with this Command which must be closed first.
System.Data.SqlClient.SqlInternalConnectionTds.ValidateConnectionForExecute(SqlCommand command)

System.Data.SqlClient.SqlInternalConnectionTds.ValidateConnectionForExecute(SqlCommand command)
System.Data.SqlClient.SqlCommand.ValidateCommand(bool async, string method)
System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, bool returnStream, TaskCompletionSource<object> completion, int timeout, out Task task, bool asyncWrite, string method)
System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary<string, object> parameterValues)
Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary<string, object> parameterValues)
Microsoft.EntityFrameworkCore.Query.QueryMethodProvider._FastQuery<TEntity>(RelationalQueryContext relationalQueryContext, ShaperCommandContext shaperCommandContext, Func<DbDataReader, DbContext, TEntity> materializer, Type contextType, IDiagnosticsLogger<Query> logger)+MoveNext()
Nop.Services.Localization.LocalizationService.ResourceValuesToDictionary(IEnumerable<LocaleStringResource> locales) in LocalizationService.cs
-
        }
        private static Dictionary<string, KeyValuePair<int, string>> ResourceValuesToDictionary(IEnumerable<LocaleStringResource> locales)
        {
            //format: <name, <id, value>>
            var dictionary = new Dictionary<string, KeyValuePair<int, string>>();
            **foreach (var locale in locales)**
            {
                var resourceName = locale.ResourceName.ToLowerInvariant();
                if (!dictionary.ContainsKey(resourceName))
                    dictionary.Add(resourceName, new KeyValuePair<int, string>(locale.Id, locale.ResourceValue));
            }
Nop.Services.Localization.LocalizationService+<>c__DisplayClass22_0.<GetAllResourceValues>b__0() in LocalizationService.cs
-
                //anyway records are loaded only for read-only operations
                var query = from l in _lsrRepository.TableNoTracking
                            orderby l.ResourceName
                            where l.LanguageId == languageId
                            select l;
                query = loadPublicLocales.Value ? query.Where(r => !r.ResourceName.StartsWith(NopLocalizationDefaults.AdminLocaleStringResourcesPrefix)) : query.Where(r => r.ResourceName.StartsWith(NopLocalizationDefaults.AdminLocaleStringResourcesPrefix));
                **return ResourceValuesToDictionary(query);**
            });
        }
        /// <summary>
        /// Gets a resource string based on the specified ResourceKey property.
        /// </summary>
EasyCaching.InMemory.DefaultInMemoryCachingProvider.BaseGet<T>(string cacheKey, Func<T> dataRetriever, TimeSpan expiration)
EasyCaching.Core.EasyCachingAbstractProvider.Get<T>(string cacheKey, Func<T> dataRetriever, TimeSpan expiration)
Nop.Core.Caching.MemoryCacheManager.Get<T>(string key, Func<T> acquire, Nullable<int> cacheTime) in MemoryCacheManager.cs
-
        /// <returns>The cached value associated with the specified key</returns>
        public T Get<T>(string key, Func<T> acquire, int? cacheTime = null)
        {
            if(cacheTime <= 0)
                return acquire();
            **return _provider.Get(key, acquire, TimeSpan.FromMinutes(cacheTime ?? NopCachingDefaults.CacheTime))**
                .Value;
        }
        /// <summary>
        /// Get a cached item. If it's not in the cache yet, then load and cache it
        /// </summary>
Nop.Services.Localization.LocalizationService.GetAllResourceValues(int languageId, Nullable<bool> loadPublicLocales) in LocalizationService.cs
-
                return rez;
            }
            //performance optimization of the site startup
            key = string.Format(loadPublicLocales.Value ? NopLocalizationDefaults.LocaleStringResourcesAllPublicCacheKey : NopLocalizationDefaults.LocaleStringResourcesAllAdminCacheKey, languageId);
            **return _cacheManager.Get(key, () =>**
            {
                //we use no tracking here for performance optimization
                //anyway records are loaded only for read-only operations
                var query = from l in _lsrRepository.TableNoTracking
                            orderby l.ResourceName
                            where l.LanguageId == languageId
Nop.Services.Localization.LocalizationService.GetResource(string resourceKey, int languageId, bool logIfNotFound, string defaultValue, bool returnEmptyIfNotFound) in LocalizationService.cs
-
            if (resourceKey == null)
                resourceKey = string.Empty;
            resourceKey = resourceKey.Trim().ToLowerInvariant();
            if (_localizationSettings.LoadAllLocaleRecordsOnStartup)
            {
                //load all records (we know they are cached)
                **var resources = GetAllResourceValues(languageId, !resourceKey.StartsWith(NopLocalizationDefaults.AdminLocaleStringResourcesPrefix, StringComparison.InvariantCultureIgnoreCase));**
                if (resources.ContainsKey(resourceKey))
                {
                    result = resources[resourceKey].Value;
                }
            }
            else
Nop.Services.Localization.LocalizationService.GetResource(string resourceKey) in LocalizationService.cs
-
        /// </summary>
        /// <param name="resourceKey">A string representing a ResourceKey.</param>
        /// <returns>A string representing the requested resource string.</returns>
        public virtual string GetResource(string resourceKey)
        {
            if (_workContext.WorkingLanguage != null)
                **return GetResource(resourceKey, _workContext.WorkingLanguage.Id);**
            return string.Empty;
        }
        /// <summary>
        /// Gets a resource string based on the specified ResourceKey property.
Nop.Services.Plugins.PluginService.InstallPlugins() in PluginService.cs
-
                    descriptor.Installed = true;
                    descriptor.ShowInPluginsList = true;
                }
                catch (Exception exception)
                {
                    //log error
                    **var message = string.Format(localizationService.GetResource("Admin.Plugins.Errors.NotInstalled"), descriptor.SystemName);**
                    _logger.Error(message, exception);
                }
            }
            //save changes
            _pluginsInfo.Save();
Nop.Web.Framework.Infrastructure.Extensions.ServiceCollectionExtensions.ConfigureApplicationServices(IServiceCollection services, IConfiguration configuration, IHostingEnvironment hostingEnvironment) in ServiceCollectionExtensions.cs
-
            TaskManager.Instance.Start();
            //log application start
            engine.Resolve<ILogger>().Information("Application started");
            //install plugins
            **engine.Resolve<IPluginService>().InstallPlugins();**
            return serviceProvider;
        }
        /// <summary>
        /// Create, bind and register as service the specified configuration parameters 
Nop.Web.Startup.ConfigureServices(IServiceCollection services) in Startup.cs
+
            return services.ConfigureApplicationServices(_configuration, _hostingEnvironment);
Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

### Raw Exception Details
System.InvalidOperationException: There is already an open DataReader associated with this Command which must be closed first.
   at System.Data.SqlClient.SqlInternalConnectionTds.ValidateConnectionForExecute(SqlCommand command)
   at System.Data.SqlClient.SqlCommand.ValidateCommand(Boolean async, String method)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider._FastQuery[TEntity](RelationalQueryContext relationalQueryContext, ShaperCommandContext shaperCommandContext, Func`3 materializer, Type contextType, IDiagnosticsLogger`1 logger)+MoveNext()
   at Nop.Services.Localization.LocalizationService.ResourceValuesToDictionary(IEnumerable`1 locales) in C:\Dev\Repos\MyPillow\src\LM\nopCommerce\Libraries\Nop.Services\Localization\LocalizationService.cs:line 126
   at Nop.Services.Localization.LocalizationService.<>c__DisplayClass22_0.<GetAllResourceValues>b__0() in C:\Dev\Repos\MyPillow\src\LM\nopCommerce\Libraries\Nop.Services\Localization\LocalizationService.cs:line 300
   at EasyCaching.InMemory.DefaultInMemoryCachingProvider.BaseGet[T](String cacheKey, Func`1 dataRetriever, TimeSpan expiration)
   at EasyCaching.Core.EasyCachingAbstractProvider.Get[T](String cacheKey, Func`1 dataRetriever, TimeSpan expiration)
   at Nop.Core.Caching.MemoryCacheManager.Get[T](String key, Func`1 acquire, Nullable`1 cacheTime) in C:\Dev\Repos\MyPillow\src\LM\nopCommerce\Libraries\Nop.Core\Caching\MemoryCacheManager.cs:line 42
   at Nop.Services.Localization.LocalizationService.GetAllResourceValues(Int32 languageId, Nullable`1 loadPublicLocales) in C:\Dev\Repos\MyPillow\src\LM\nopCommerce\Libraries\Nop.Services\Localization\LocalizationService.cs:line 291
   at Nop.Services.Localization.LocalizationService.GetResource(String resourceKey, Int32 languageId, Boolean logIfNotFound, String defaultValue, Boolean returnEmptyIfNotFound) in C:\Dev\Repos\MyPillow\src\LM\nopCommerce\Libraries\Nop.Services\Localization\LocalizationService.cs:line 336
   at Nop.Services.Localization.LocalizationService.GetResource(String resourceKey) in C:\Dev\Repos\MyPillow\src\LM\nopCommerce\Libraries\Nop.Services\Localization\LocalizationService.cs:line 312
   at Nop.Services.Plugins.PluginService.InstallPlugins() in C:\Dev\Repos\MyPillow\src\LM\nopCommerce\Libraries\Nop.Services\Plugins\PluginService.cs:line 439
   at Nop.Web.Framework.Infrastructure.Extensions.ServiceCollectionExtensions.ConfigureApplicationServices(IServiceCollection services, IConfiguration configuration, IHostingEnvironment hostingEnvironment) in C:\Dev\Repos\MyPillow\src\LM\nopCommerce\Presentation\Nop.Web.Framework\Infrastructure\Extensions\ServiceCollectionExtensions.cs:line 97
   at Nop.Web.Startup.ConfigureServices(IServiceCollection services) in C:\Dev\Repos\MyPillow\src\LM\nopCommerce\Presentation\Nop.Web\Startup.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
`

**Comment by skoshelev** [comment]
Hi @toddca 
I could not repeat the problem on the latest version of the nopCommerce, I tried to install 16 plugins 4 of which add tables to the database, no problems, all 16 are installed and working

Could you please try reproduce this error again? And if it possible provide us more details to reproduce

**Comment by skoshelev** [comment]
Can't reproduce

Closed #3909
