### ISSUE TITLE
Square Plugin: Failed to get the card nonce

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#3919]
nopCommerce version: 
4.20

Steps to reproduce the problem: 
1) Enable Square in production
2) Check out using a valid CC
3) Get Failed to get the card nonce

Error 1:
`Nop.Core.NopException: Failed to get the card nonce
   at Nop.Plugin.Payments.Square.SquarePaymentMethod.CreateChargeRequest(ProcessPaymentRequest paymentRequest, Boolean isRecurringPayment)
   at Nop.Plugin.Payments.Square.SquarePaymentMethod.ProcessPayment(ProcessPaymentRequest paymentRequest, Boolean isRecurringPayment)
   at Nop.Plugin.Payments.Square.SquarePaymentMethod.ProcessPayment(ProcessPaymentRequest processPaymentRequest)
   at Nop.Services.Payments.PaymentService.ProcessPayment(ProcessPaymentRequest processPaymentRequest) in C:\Users\dootc\Documents\Visual Studio 2019\Websites\nopCommerce_4.20_Source\Libraries\Nop.Services\Payments\PaymentService.cs:line 67
   at Nop.Services.Orders.OrderProcessingService.GetProcessPaymentResult(ProcessPaymentRequest processPaymentRequest, PlaceOrderContainer details) in C:\Users\dootc\Documents\Visual Studio 2019\Websites\nopCommerce_4.20_Source\Libraries\Nop.Services\Orders\OrderProcessingService.cs:line 1396
   at Nop.Services.Orders.OrderProcessingService.PlaceOrder(ProcessPaymentRequest processPaymentRequest) in C:\Users\dootc\Documents\Visual Studio 2019\Websites\nopCommerce_4.20_Source\Libraries\Nop.Services\Orders\OrderProcessingService.cs:line 1544`

Error 2:
`Error while placing order. Error 1: Failed to get the card nonce.`

**Local Host Repeat:
1) Turn OFF Use one page checkout - Get the error
2) Turn ON Use one page checkout - Error goes away**

Also, my "sandbox" access token does not start with "sandbox-".

**Comment by Ochapparel** [comment]
i was loading js in the header. moved to footer and appeared to fix it.
