### ISSUE TITLE
Square Payment Plugin errors invalid culture 4096 0x1000 unsupported

### ISSUE THREAD

**Issue by rodolphito** [nopSolutions/nopCommerce#4204]
nopCommerce version: 4.30

Steps to reproduce the problem: Install Square payment plugin and set up a sandbox account, add a product to your cart, go checkout, select Square, enter card 4111 1111 1111 1111, 12/21, CVV 111, zip 12345. Click Proceed, and this error will occur:

```
Culture is not supported. Parameter name: culture 4096 (0x1000) is an invalid culture identifier.
```

Now go to the admin backend system logs, and there will be an exception logged:

```
System.Globalization.CultureNotFoundException: Culture is not supported.
Parameter name: culture
4096 (0x1000) is an invalid culture identifier.
	at System.Globalization.CultureData.GetCultureData(Int32 culture, Boolean bUseUserOverride)
	at System.Globalization.RegionInfo..ctor(Int32 culture)
	at Nop.Plugin.Payments.Square.SquarePaymentMethod.CheckSupportCurrency(Currency currency) in /src/Plugins/Nop.Plugin.Payments.Square/SquarePaymentMethod.cs:line 101
	at Nop.Plugin.Payments.Square.SquarePaymentMethod.CreateChargeRequest(ProcessPaymentRequest paymentRequest, Boolean isRecurringPayment) in /src/Plugins/Nop.Plugin.Payments.Square/SquarePaymentMethod.cs:line 203
	at Nop.Plugin.Payments.Square.SquarePaymentMethod.ProcessPayment(ProcessPaymentRequest paymentRequest, Boolean isRecurringPayment) in /src/Plugins/Nop.Plugin.Payments.Square/SquarePaymentMethod.cs:line 146
	at Nop.Plugin.Payments.Square.SquarePaymentMethod.ProcessPayment(ProcessPaymentRequest processPaymentRequest) in /src/Plugins/Nop.Plugin.Payments.Square/SquarePaymentMethod.cs:line 386
	at Nop.Services.Payments.PaymentService.ProcessPayment(ProcessPaymentRequest processPaymentRequest) in /src/Libraries/Nop.Services/Payments/PaymentService.cs:line 67
	at Nop.Services.Orders.OrderProcessingService.GetProcessPaymentResult(ProcessPaymentRequest processPaymentRequest, PlaceOrderContainer details) in /src/Libraries/Nop.Services/Orders/OrderProcessingService.cs:line 1402
	at Nop.Services.Orders.OrderProcessingService.PlaceOrder(ProcessPaymentRequest processPaymentRequest) in /src/Libraries/Nop.Services/Orders/OrderProcessingService.cs:line 1550
```

The relevant function:

```
private bool CheckSupportCurrency(Currency currency)
{
	foreach (var culture in CultureInfo.GetCultures(CultureTypes.SpecificCultures))
	{
		var regionInfo = new RegionInfo(culture.LCID); // <-- ERROR ON THIS LINE
		if (currency.CurrencyCode.Equals(regionInfo.ISOCurrencySymbol, StringComparison.InvariantCultureIgnoreCase))
		{
			return true;
		}
	}

	return false;
}
```

I have worked around this by just making it return true always.

Should this be wrapped in a try/catch, or what? I searched around to see if it was a misconfiguration, but couldn't find anything.

**Comment by DmitriyKulagin** [comment]
Closed #4204
