### ISSUE TITLE
4.30 SquareUp "Location is a required parameter for payment requests"

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#4482]
nopCommerce version: 
4.30

Steps to reproduce the problem: 
1) Setup SquareUp Sandbox with 2019-9-25 version (fyi, this is the last one in the support list...may want to update)
2) Configure SquareUp
3) Add an Item and check out
4) Get the bellow errors

`Short message	
Square payment error: Location is a required parameter for payment requests.
Full message	
Nop.Core.NopException: Location is a required parameter for payment requests
   at Nop.Plugin.Payments.Square.Services.SquarePaymentManager.Charge(ExtendedChargeRequest chargeRequest, Int32 storeId)`

`Log level	
Error
Short message	
Location is a required parameter for payment requests
Full message	
Nop.Core.NopException: Location is a required parameter for payment requests
   at Nop.Plugin.Payments.Square.SquarePaymentMethod.ProcessPayment(ProcessPaymentRequest paymentRequest, Boolean isRecurringPayment)
   at Nop.Plugin.Payments.Square.SquarePaymentMethod.ProcessPayment(ProcessPaymentRequest processPaymentRequest)
   at Nop.Services.Payments.PaymentService.ProcessPayment(ProcessPaymentRequest processPaymentRequest) in C:\Users\Cody-PC\Documents\Visual Studio 2019\Websites\nopCommerce_4.30_beta_Source\Libraries\Nop.Services\Payments\PaymentService.cs:line 70
   at Nop.Services.Orders.OrderProcessingService.GetProcessPaymentResult(ProcessPaymentRequest processPaymentRequest, PlaceOrderContainer details) in C:\Users\Cody-PC\Documents\Visual Studio 2019\Websites\nopCommerce_4.30_beta_Source\Libraries\Nop.Services\Orders\OrderProcessingService.cs:line 1424
   at Nop.Services.Orders.OrderProcessingService.PlaceOrder(ProcessPaymentRequest processPaymentRequest) in C:\Users\Cody-PC\Documents\Visual Studio 2019\Websites\nopCommerce_4.30_beta_Source\Libraries\Nop.Services\Orders\OrderProcessingService.cs:line 1571
IP address	
127.0.0.1`

`Log level	
Error
Short message	
Error while placing order. Error 1: Location is a required parameter for payment requests.
Full message	
IP address	
127.0.0.1
Customer	sales@ochapparel.com
Page URL	
http://localhost:15536/checkout/OpcConfirmOrder/`

SquareSetup:
![image](https://user-images.githubusercontent.com/20989983/78513184-d2d1cd80-7777-11ea-819f-a7b4f735ff53.png)

![image](https://user-images.githubusercontent.com/20989983/78513200-eed56f00-7777-11ea-8e67-e21927774fea.png)

![image](https://user-images.githubusercontent.com/20989983/78513214-06145c80-7778-11ea-95bf-3210d7d984ee.png)

**Comment by holydk** [comment]
We updated (#4336) the Square SDK to 2020-03-25 (Latest) version. You must make sure that you are using the correct sandbox application id, sandbox access token and the latest API version in your square application.

Closed #4482
