### ISSUE TITLE
Redis fails on 4.30

### ISSUE THREAD

**Issue by vachkata** [nopSolutions/nopCommerce#4659]
System.ObjectDisposedException
  HResult=0x80131622
  Message=Cannot access a disposed object.
Object name: 'Microsoft.Extensions.Caching.Memory.MemoryCache'.
  Source=Microsoft.Extensions.Caching.Memory
  StackTrace:
   at Microsoft.Extensions.Caching.Memory.MemoryCache.CheckDisposed()
   at Microsoft.Extensions.Caching.Memory.MemoryCache.TryGetValue(Object key, Object& result)
   at Nop.Core.Caching.MemoryCacheManager.IsSet(CacheKey key) in C:\projects\nop\nopCommerce\src\Libraries\Nop.Core\Caching\MemoryCacheManager.cs:line 148
   at Nop.Core.Caching.RedisCacheManager.IsSet(CacheKey key) in C:\projects\nop\nopCommerce\src\Libraries\Nop.Core\Caching\RedisCacheManager.cs:line 249
   at Nop.Core.Caching.RedisCacheManager.Get[T](CacheKey key, Func`1 acquire) in C:\projects\nop\nopCommerce\src\Libraries\Nop.Core\Caching\RedisCacheManager.cs:line 206
   at Nop.Services.Configuration.SettingService.GetAllSettingsDictionary() in C:\projects\nop\nopCommerce\src\Libraries\Nop.Services\Configuration\SettingService.cs:line 53
   at Nop.Services.Configuration.SettingService.GetSettingByKey[T](String key, T defaultValue, Int32 storeId, Boolean loadSharedValueIfNotFound) in C:\projects\nop\nopCommerce\src\Libraries\Nop.Services\Configuration\SettingService.cs:line 264
   at Nop.Plugin.Tax.FixedOrByCountryStateZip.FixedOrByCountryStateZipTaxProvider.GetTaxRate(TaxRateRequest taxRateRequest) in C:\projects\nop\nopCommerce\src\Plugins\Nop.Plugin.Tax.FixedOrByCountryStateZip\FixedOrByCountryStateZipTaxProvider.cs:line 96
   at Nop.Services.Tax.TaxService.GetTaxRate(Product product, Int32 taxCategoryId, Customer customer, Decimal price, Decimal& taxRate, Boolean& isTaxable) in C:\projects\nop\nopCommerce\src\Libraries\Nop.Services\Tax\TaxService.cs:line 308
   at Nop.Services.Tax.TaxService.GetProductPrice(Product product, Int32 taxCategoryId, Decimal price, Boolean includingTax, Customer customer, Boolean priceIncludesTax, Decimal& taxRate) in C:\projects\nop\nopCommerce\src\Libraries\Nop.Services\Tax\TaxService.cs:line 405
   at Nop.Services.Tax.TaxService.GetProductPrice(Product product, Decimal price, Boolean includingTax, Customer customer, Decimal& taxRate) in C:\projects\nop\nopCommerce\src\Libraries\Nop.Services\Tax\TaxService.cs:line 379
   at Nop.Services.Tax.TaxService.GetProductPrice(Product product, Decimal price, Customer customer, Decimal& taxRate) in C:\projects\nop\nopCommerce\src\Libraries\Nop.Services\Tax\TaxService.cs:line 362
   at Nop.Services.Tax.TaxService.GetProductPrice(Product product, Decimal price, Decimal& taxRate) in C:\projects\nop\nopCommerce\src\Libraries\Nop.Services\Tax\TaxService.cs:line 347
   at Nop.Web.Factories.ProductModelFactory.PrepareSimpleProductOverviewPriceModel(Product product, ProductPriceModel priceModel) in C:\projects\nop\nopCommerce\src\Presentation\Nop.Web\Factories\ProductModelFactory.cs:line 293
   at Nop.Web.Factories.ProductModelFactory.PrepareProductOverviewPriceModel(Product product, Boolean forceRedirectionAfterAddingToCart) in C:\projects\nop\nopCommerce\src\Presentation\Nop.Web\Factories\ProductModelFactory.cs:line 228
   at Nop.Web.Factories.ProductModelFactory.PrepareProductOverviewModels(IEnumerable`1 products, Boolean preparePriceModel, Boolean preparePictureModel, Nullable`1 productThumbPictureSize, Boolean prepareSpecificationAttributes, Boolean forceRedirectionAfterAddingToCart) in C:\projects\nop\nopCommerce\src\Presentation\Nop.Web\Factories\ProductModelFactory.cs:line 1108
   at Nop.Web.Components.HomepageProductsViewComponent.Invoke(Nullable`1 productThumbPictureSize) in C:\projects\nop\nopCommerce\src\Presentation\Nop.Web\Components\HomepageProducts.cs:line 42
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeSyncCore(ObjectMethodExecutor executor, ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.<InvokeAsync>d__5.MoveNext()

My source code is from a couple of days ago.
I am getting this exception both from Azure server and from Visual Studio.
It is on the demo database.
The store shows the home page, then after couple of clicks (apparel and one more level down) this appears and only web app reset recovers it. It is a basic redis plan (250MB).
Not sure if it is my configuration problem or a common source code error.

**Comment by ghominejad** [comment]
I heard that you don't recommend using `redis` in high scaling scenarios. Is it possible using `redis` with hundreds of nodes?  Can i count on it?

Thanks

**Comment by skoshelev** [comment]
Closed #4659
