### ISSUE TITLE
Failed on startup on Linux 

### ISSUE THREAD

**Issue by ratulbside** [nopSolutions/nopCommerce#4933]
nopCommerce version: 4.30

Steps to reproduce the problem: 

Install .NET Core on a fresh Linux OS (CentOS)  and put nopCommerce files on a web directory (and prepare all the necessary steps to run nopCommerce on Linux). It fails to start while browsing. 

Then test it with `dotnet /home/user/public_html/Nop.Web.dll`

Output:

`crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]
      Application startup exception
**System.IO.DirectoryNotFoundException: /root/Themes/**
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Nop.Web.Framework.Infrastructure.Extensions.ApplicationBuilderExtensions.UseNopStaticFiles(IApplicationBuilder application)
   at Nop.Web.Framework.Infrastructure.NopCommonStartup.Configure(IApplicationBuilder application)
   at Nop.Core.Infrastructure.NopEngine.ConfigureRequestPipeline(IApplicationBuilder application)
   at Nop.Web.Framework.Infrastructure.Extensions.ApplicationBuilderExtensions.ConfigureRequestPipeline(IApplicationBuilder application)
   at Nop.Web.Startup.Configure(IApplicationBuilder application)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
**Unhandled exception. System.IO.DirectoryNotFoundException: /root/Themes/**
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Nop.Web.Framework.Infrastructure.Extensions.ApplicationBuilderExtensions.UseNopStaticFiles(IApplicationBuilder application)
   at Nop.Web.Framework.Infrastructure.NopCommonStartup.Configure(IApplicationBuilder application)
   at Nop.Core.Infrastructure.NopEngine.ConfigureRequestPipeline(IApplicationBuilder application)
   at Nop.Web.Framework.Infrastructure.Extensions.ApplicationBuilderExtensions.ConfigureRequestPipeline(IApplicationBuilder application)
   at Nop.Web.Startup.Configure(IApplicationBuilder application)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Nop.Web.Program.Main(String[] args)
Aborted`

So, the code unable to find the 'Themes' folder.

**Comment by skoshelev** [comment]
Hi @ratulbside. Please check that the Themes directory exists, and the user on whose behalf the process is running has rights to it. Also, try to go to the directory with Nop.Web.dll and run the site from it.

**Comment by skoshelev** [comment]
Can't reproduce

Closed #4933

**Comment by ozgurerdogan** [comment]
I am having the same issue.

**Comment by Fatihk** [comment]
> 

You should write source folder path in launch.json file.

            "cwd": "${workspaceFolder}/Presentation/Nop.Web",

**Comment by sinanopcommerce** [comment]
> Hi @ratulbside. Please check that the Themes directory exists, and the user on whose behalf the process is running has rights to it. Also, try to go to the directory with Nop.Web.dll and run the site from it.

How you think that someone launches e-commerce without a theme folder.


Unhandled exception. System.IO.DirectoryNotFoundException: /root/Themes/
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Nop.Web.Framework.Infrastructure.Extensions.ApplicationBuilderExtensions.UseNopWebOptimizer(IApplicationBuilder application)
