### ISSUE TITLE
contact us email not working

### ISSUE THREAD

**Issue by mardev-code** [nopSolutions/nopCommerce#5082]
nopCommerce version: 4.3

Steps to reproduce the problem: 

1. store with one or more Vendors

2. Allow customers to contact vendors is active 

3. Customer send Email via Contact form to Vendor.

4. Customer and Vendor have gmail.com Damain Store Default Email Account has an other Domain email Account 

Result:
Error sending e-mail. Delivery is not allowed to this address.
`MailKit.Net.Smtp.SmtpCommandException: Delivery is not allowed to this address.
   at MailKit.Net.Smtp.SmtpClient.OnRecipientNotAccepted(MimeMessage message, MailboxAddress mailbox, SmtpResponse response)
   at MailKit.Net.Smtp.SmtpClient.ProcessRcptToResponse(MimeMessage message, MailboxAddress mailbox, SmtpResponse response)
   at MailKit.Net.Smtp.SmtpClient.RcptToAsync(FormatOptions options, MimeMessage message, MailboxAddress mailbox, Boolean doAsync, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.SendAsync(FormatOptions options, MimeMessage message, MailboxAddress sender, IList`1 recipients, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.Net.Smtp.SmtpClient.SendAsync(FormatOptions options, MimeMessage message, MailboxAddress sender, IList`1 recipients, Boolean doAsync, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.Net.Smtp.SmtpClient.Send(FormatOptions options, MimeMessage message, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.MailTransport.Send(MimeMessage message, CancellationToken cancellationToken, ITransferProgress progress)
   at Nop.Services.Messages.EmailSender.SendEmail(EmailAccount emailAccount, String subject, String body, String fromAddress, String fromName, String toAddress, String toName, String replyTo, String replyToName, IEnumerable`1 bcc, IEnumerable`1 cc, String attachmentFilePath, String attachmentFileName, Int32 attachedDownloadId, IDictionary`2 headers)
   at Nop.Services.Messages.QueuedMessagesSendTask.Execute()`

**Comment by AndreiMaz** [comment]
We cannot reproduce this "Delivery is not allowed to this address" issue.
