### ISSUE TITLE
 GetOrCreateSearchEngineUser System.IndexOutOfRangeException: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by dhruvpiesoftware** [nopSolutions/nopCommerce#5248]
nopCommerce version: 4.30
Steps to reproduce the problem: Suddenly system starts throwing below exception for all pages.

2020-12-26T05:34:09.393055222Z: [INFO]        An unhandled exception has occurred while executing the request.
2020-12-26T05:34:09.393062922Z: [INFO]  System.IndexOutOfRangeException: Index was outside the bounds of the array.
2020-12-26T05:34:09.393068923Z: [INFO]     at System.Data.SqlClient.SqlDataReader.CheckHeaderIsReady(Int32 columnIndex, Boolean permitAsync, String methodName)
2020-12-26T05:34:09.393074723Z: [INFO]     at System.Data.SqlClient.SqlDataReader.IsDBNull(Int32 i)
2020-12-26T05:34:09.393081023Z: [INFO]     at LinqToDB.Expressions.ConvertFromDataReaderExpression.ColumnReader.GetValue(IDataReader dataReader)
2020-12-26T05:34:09.393099224Z: [INFO]     at lambda_method(Closure , IQueryRunner , IDataReader )
2020-12-26T05:34:09.393105125Z: [INFO]     at LinqToDB.Linq.QueryRunner.Mapper`1.Map(IQueryRunner queryRunner, IDataReader dataReader)
2020-12-26T05:34:09.393111025Z: [INFO]     at LinqToDB.Linq.QueryRunner.ExecuteQuery[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Int32 queryNumber)+MoveNext()
2020-12-26T05:34:09.393117126Z: [INFO]     at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
2020-12-26T05:34:09.393122926Z: [INFO]     at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
2020-12-26T05:34:09.393128626Z: [INFO]     at LinqToDB.Linq.Builder.FirstSingleBuilder.FirstSingleContext.<>c__DisplayClass4_0`1.<GetFirstOrDefaultElement>b__0(IDataContext db, Expression expr, Object[] ps)
2020-12-26T05:34:09.393135227Z: [INFO]     at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
2020-12-26T05:34:09.393140927Z: [INFO]     at Nop.Services.Customers.CustomerService.GetOrCreateSearchEngineUser()
2020-12-26T05:34:09.393146527Z: [INFO]     at Nop.Web.Framework.WebWorkContext.get_CurrentCustomer()
2020-12-26T05:34:09.393152028Z: [INFO]     at Nop.Web.Framework.WebWorkContext.get_WorkingLanguage()
2020-12-26T05:34:09.393157628Z: [INFO]     at Nop.Web.Framework.Globalization.CultureMiddleware.SetWorkingCulture(IWebHelper webHelper, IWorkContext workContext)
2020-12-26T05:34:09.393163328Z: [INFO]     at Nop.Web.Framework.Globalization.CultureMiddleware.Invoke(HttpContext context, IWebHelper webHelper, IWorkContext workContext)
2020-12-26T05:34:09.393169129Z: [INFO]     at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
2020-12-26T05:34:09.393174729Z: [INFO]     at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
2020-12-26T05:34:09.393180429Z: [INFO]     at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
2020-12-26T05:34:09.393186830Z: [INFO]     at Nop.Services.Installation.InstallUrlMiddleware.Invoke(HttpContext context, IWebHelper webHelper)
2020-12-26T05:34:09.393192630Z: [INFO]     at Nop.Services.Common.KeepAliveMiddleware.Invoke(HttpContext context, IWebHelper webHelper)
2020-12-26T05:34:09.393198231Z: [INFO]     at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
2020-12-26T05:34:09.393203831Z: [INFO]     at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
2020-12-26T05:34:09.393209531Z: [INFO]     at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
2020-12-26T05:34:09.393215132Z: [INFO]     at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2020-12-26T05:34:09.414437156Z: [INFO]  [41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[3]

**Comment by exileDev** [comment]
I can't reproduce this. It looks like a database schema has custom changes.
Closed #5248
