### ISSUE TITLE
PlatformNotSupportedException on home page when run on centos 8 or linux docker

### ISSUE THREAD

**Issue by chensiel** [nopSolutions/nopCommerce#5273]
I git 4.4.0 develop branch and build to run  on centos 8.

There are some exception on home page. No errors on admin pages, no errors on home page when debugging in vs 2019

Do anyone have test it on centos 8?

nopCommerce version: 4.4.0 develop branch

Steps to reproduce the problem: build and run on linux or linux docker

OS version: centos 8 Linux 4.18.0-240.1.1.el8_3.x86_64 

Runtime: dotnet 5.0.1

Exception trace stack:
System.PlatformNotSupportedException: The named version of this synchronization primitive is not supported on this platform.
   at System.Threading.Semaphore.CreateSemaphoreCore(Int32 initialCount, Int32 maximumCount, String name, Boolean& createdNew)
   at System.Threading.Semaphore..ctor(Int32 initialCount, Int32 maximumCount, String name, Boolean& createdNew)
   at System.Threading.Semaphore..ctor(Int32 initialCount, Int32 maximumCount, String name)
   at Nop.Services.Media.PictureService.GetPictureUrlAsync(Picture picture, Int32 targetSize, Boolean showDefaultPicture, String storeLocation, PictureType defaultPictureType) in /src/Libraries/Nop.Services/Media/PictureService.cs:line 583
   at Nop.Web.Factories.CatalogModelFactory.<>c__DisplayClass43_1.<<PrepareHomepageCategoryModelsAsync>b__7>d.MoveNext() in /src/Presentation/Nop.Web/Factories/CatalogModelFactory.cs:line 711
--- End of stack trace from previous location ---
   at Nop.Core.Caching.MemoryCacheManager.GetAsync[T](CacheKey key, Func`1 acquire) in /src/Libraries/Nop.Core/Caching/MemoryCacheManager.cs:line 122
   at Nop.Web.Factories.CatalogModelFactory.<>c__DisplayClass43_0.<<PrepareHomepageCategoryModelsAsync>b__1>d.MoveNext() in /src/Presentation/Nop.Web/Factories/CatalogModelFactory.cs:line 706
--- End of stack trace from previous location ---
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIteratorWithTask`2.MoveNextCore() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Select.cs:line 381
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:line 77
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:line 77
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|620_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|620_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
   at Nop.Web.Factories.CatalogModelFactory.<>c__DisplayClass43_0.<<PrepareHomepageCategoryModelsAsync>b__0>d.MoveNext() in /src/Presentation/Nop.Web/Factories/CatalogModelFactory.cs:line 688
--- End of stack trace from previous location ---
   at Nop.Core.Caching.MemoryCacheManager.GetAsync[T](CacheKey key, Func`1 acquire) in /src/Libraries/Nop.Core/Caching/MemoryCacheManager.cs:line 122
   at Nop.Web.Factories.CatalogModelFactory.PrepareHomepageCategoryModelsAsync() in /src/Presentation/Nop.Web/Factories/CatalogModelFactory.cs:line 687
   at Nop.Web.Components.HomepageCategoriesViewComponent.InvokeAsync() in /src/Presentation/Nop.Web/Components/HomepageCategories.cs:line 20
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsyncCore(ObjectMethodExecutor executor, ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsync(ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper.InvokeCoreAsync(ViewComponentDescriptor descriptor, Object arguments)
   at AspNetCore.Views_Home_Index.ExecuteAsync() in /app/Views/Home/Index.cshtml:line 12
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|27_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at WebMarkupMin.AspNetCore5.WebMarkupMinMiddleware.ProcessAsync(HttpContext context, Boolean useMinification, Boolean useCompression)
   at WebMarkupMin.AspNetCore5.WebMarkupMinMiddleware.ProcessAsync(HttpContext context, Boolean useMinification, Boolean useCompression)
   at WebMarkupMin.AspNetCore5.WebMarkupMinMiddlewareBase.Invoke(HttpContext context)
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 125
   at Nop.Services.Authentication.AuthenticationMiddleware.InvokeAsync(HttpContext context) in /src/Libraries/Nop.Services/Authentication/AuthenticationMiddleware.cs:line 95
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Nop.Services.Installation.InstallUrlMiddleware.InvokeAsync(HttpContext context, IWebHelper webHelper) in /src/Libraries/Nop.Services/Installation/InstallUrlMiddleware.cs:line 53
   at Nop.Services.Common.KeepAliveMiddleware.InvokeAsync(HttpContext context, IWebHelper webHelper) in /src/Libraries/Nop.Services/Common/KeepAliveMiddleware.cs:line 50
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by skoshelev** [comment]
Hi @chensiel. If you run and test code in VS 2019 on windows, you should know that a project for windows is automatically built that will not work in a Linux environment. You either need to explicitly specify the platform for building or build sources on the target platform.

also note that 4.40 is in development and may not work stably or will not run on specific platforms. We haven't tested the code in a UNIX environment yet.

**Comment by chensiel** [comment]
Hi @skoshelev, I published it for a linux target as other asp.net core project which works fine on linux.
And the docker image were built by a linux machine, it has the same exception.

**Comment by skoshelev** [comment]
@chensiel, Possible this issue related to this ticket https://github.com/dotnet/runtime/issues/5211. We tested 4.30 on ubuntu and it works well, could you please try start 4.30 on your centos server

**Comment by chensiel** [comment]
@skoshelev yes, 4.30 works well on centos.

**Comment by celer1tas** [comment]
I experience the same issue when creating a docker image using:
- mcr.microsoft.com/dotnet/aspnet:5.0.2-buster-slim AS runtime 
or 
- mcr.microsoft.com/dotnet/aspnet:5.0-alpine AS runtime

**Comment by AndreiMaz** [comment]
@skoshelev https://www.nopcommerce.com/en/boards/topic/90152/nopcommerce-440-bug-fixes-and-improvements/page/3#281035

**Comment by skoshelev** [comment]
Closed #5273
