### ISSUE TITLE
rewardpoints/history mysql exception : Non-negative number required. (Parameter 'count')

### ISSUE THREAD

**Issue by nextfool** [nopSolutions/nopCommerce#5605]
nopCommerce version: 4.40.3

env: Ubuntu 20.04 + mysql 8

Steps to reproduce the problem: 

For any user, if there is no "reward points" for him(yet),  the "rewardpoints/history" page works fine, showing a message says there is no reword points.

But if the user completes an order with reword points, this page throws an exception. In fact if we go to admin and edit the customer's info, there is an ajax post call to get the user's reward points history which is also returned with exactly the same exception. Bellow is the detail:

`System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'count')
   at System.Text.UTF8Encoding.GetString(Byte[] bytes, Int32 index, Int32 count)
   at MySql.Data.MySqlClient.NativeDriver.ReadColumnValue(Int32 index, MySqlField field, IMySqlValue valObject)
   at MySql.Data.MySqlClient.ResultSet.ReadColumnData(Boolean outputParms)
   at MySql.Data.MySqlClient.ResultSet.NextRow(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlDataReader.Read()
   at System.Data.Common.DbDataReader.ReadAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at LinqToDB.Linq.QueryRunner.ExecuteQueryAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber, Func`2 func, TakeSkipDelegate skipAction, TakeSkipDelegate takeAction, CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.ExecuteQueryAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber, Func`2 func, TakeSkipDelegate skipAction, TakeSkipDelegate takeAction, CancellationToken cancellationToken)
   at LinqToDB.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
   at LinqToDB.AsyncExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken token)
   at System.Linq.AsyncIQueryableExtensions.ToPagedListAsync[T](IQueryable`1 source, Int32 pageIndex, Int32 pageSize, Boolean getOnlyTotalCount) in /home/***hide-my-info***/src/Libraries/Nop.Data/Extensions/AsyncIQueryableExtensions.cs:line 654
   at Nop.Services.Orders.RewardPointService.GetRewardPointsHistoryAsync(Int32 customerId, Nullable`1 storeId, Boolean showNotActivated, Nullable`1 orderGuid, Int32 pageIndex, Int32 pageSize) in /home/***hide-my-info***/src/Libraries/Nop.Services/Orders/RewardPointService.cs:line 168
   at Nop.Web.Factories.OrderModelFactory.PrepareCustomerRewardPointsAsync(Nullable`1 page) in /home/***hide-my-info***/src/Presentation/Nop.Web/Factories/OrderModelFactory.cs:line 596
   at Nop.Web.Controllers.OrderController.CustomerRewardPoints(Nullable`1 pageNumber) in /home/***hide-my-info***/src/Presentation/Nop.Web/Controllers/OrderController.cs:line 152
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at WebMarkupMin.AspNetCore5.WebMarkupMinMiddlewareBase.Invoke(HttpContext context)
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 104
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Nop.Services.Authentication.AuthenticationMiddleware.InvokeAsync(HttpContext context) in /home/***hide-my-info***/src/Libraries/Nop.Services/Authentication/AuthenticationMiddleware.cs:line 94
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Nop.Services.Installation.InstallUrlMiddleware.InvokeAsync(HttpContext context, IWebHelper webHelper) in /home/***hide-my-info***/src/Libraries/Nop.Services/Installation/InstallUrlMiddleware.cs:line 52
   at Nop.Services.Common.KeepAliveMiddleware.InvokeAsync(HttpContext context, IWebHelper webHelper) in /home/***hide-my-info***/src/Libraries/Nop.Services/Common/KeepAliveMiddleware.cs:line 49
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)`

**Comment by nextfool** [comment]
sorry I forget to mention that I did some customization over the default config:

![2021-04-12_11-51](https://user-images.githubusercontent.com/2167369/114338388-8d638f80-9b85-11eb-9d44-522de285ca7c.png)

**Comment by nextfool** [comment]
hi, just FYI: https://stackoverflow.com/questions/64473659/why-am-i-getting-an-error-when-connecting-to-mysql-in-c-sharp-net-core-3

I am currently also investigating this..

**Comment by nextfool** [comment]
@exileDev  Hi, so after I downgrade the Mysql.Data nuget package to 8.0.21, it works now!

**Comment by nextfool** [comment]
@exileDev Hi, like the accepted answer in above SO post sais, the "MySqlConnector.dll" is a more robust solution for dotnet core + mysql. I personally had some really bad experience with the official "Mysql.Data.dll" before. IMHO it never been a good choice for project like Nop to use this inmature package, will you consider to replace it with "MysqlConnector" in the future?

**Comment by exileDev** [comment]
@exileDev Yes, we'll consider migration ability.

**Comment by exileDev** [comment]
We've updated the Mysql.Data package, but anyway, consider migration shortly.
