### ISSUE TITLE
The "Delete guests" scheduled task failed with the "One or more errors occurred. (Table 'tmp_guestsToDelete' already exists)" 

### ISSUE THREAD

**Issue by nextfool** [nopSolutions/nopCommerce#5625]
nopCommerce version: 4.40.3
env: Ubuntu 20.04 + mysql 8
Steps to reproduce the problem: 
Hi, today I found out that nop generates a lot of error log as following:

Error
Short message
The "Delete guests" scheduled task failed with the "One or more errors occurred. (Table 'tmp_guestsToDelete' already exists)" error (Task type: "Nop.Services.Customers.DeleteGuestsTask, Nop.Services". Store name: "mystore-domain". Task run address: "https://mystore-domain.com/scheduletask/runtask").
Full message
System.AggregateException: One or more errors occurred. (Table 'tmp_guestsToDelete' already exists)
---> MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'tmp_guestsToDelete' already exists
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at LinqToDB.Data.DataConnection.ExecuteNonQuery()
   at LinqToDB.Linq.QueryRunner.NonQueryQuery(Query query, IDataContext dataContext, Expression expr, Object[] parameters, Object[] preambles)
   at LinqToDB.Linq.QueryRunner.<>c__DisplayClass32_0.<SetNonQueryQuery>b__0(IDataContext db, Expression expr, Object[] ps, Object[] preambles)
   at LinqToDB.Linq.QueryRunner.CreateTable`1.Query(IDataContext dataContext, String tableName, String serverName, String databaseName, String schemaName, String statementHeader, String statementFooter, DefaultNullable defaultNullable, TableOptions tableOptions)
   at LinqToDB.TempTable`1..ctor(IDataContext db, IQueryable`1 items, String tableName, String databaseName, String schemaName, Action`1 action, String serverName, TableOptions tableOptions)
   at Nop.Data.DataProviders.BaseDataProvider.CreateTempDataStorageAsync[TItem](String storeKey, IQueryable`1 query)
   at Nop.Services.Customers.CustomerService.DeleteGuestCustomersAsync(Nullable`1 createdFromUtc, Nullable`1 createdToUtc, Boolean onlyWithoutShoppingCart)
   at Nop.Services.Customers.DeleteGuestsTask.ExecuteAsync()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Nop.Services.Tasks.Task.ExecuteTask()
   at Nop.Core.Caching.MemoryCacheManager.PerformActionWithLock(String key, TimeSpan expirationTime, Action action)
   at Nop.Services.Tasks.Task.ExecuteAsync(Boolean throwException, Boolean ensureRunOncePerPeriod)
IP address
127.0.0.1

I am not sure if this is all right..

**Comment by AndreiMaz** [comment]
Just manually delete the table - DROP TABLE #tmp_guestsToDelete

**Comment by RomanovM** [comment]
The same as #5556

**Comment by cklenk** [comment]
I still have this issue in version 4.6.4
![image](https://github.com/nopSolutions/nopCommerce/assets/12185742/6bd9caea-b72c-4f9a-bc86-a1da311cb74d)

**Comment by AndreiMaz** [comment]
@cklenk Just manually delete the table - DROP TABLE #tmp_guestsToDelete

**Comment by RomanovM** [comment]
See also suggestion in [this forum post](https://www.nopcommerce.com/boards/topic/102741/scheduled-task-and-manual-execution-of-task-to-delete-guest-accounts-fail)
