### ISSUE TITLE
Scheduled Tasks are failing on startup on Linux

### ISSUE THREAD

**Issue by exileDev** [nopSolutions/nopCommerce#5656]
nopCommerce version: 4.40.3

Steps to reproduce the problem: 
> The problem is that if I have enabled scheduled task (any), then nopCommerce won't start at all on my Debian 10 server.
If I run manually, they work.
I connected windows machine to the same DB and it started successfully.
Below is stack trace from Linux machine

```csharp
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
at Nop.Services.Tasks.TaskThread.TimerHandler(Object state)
at System.Threading.TimerQueueTimer.<>c.<.cctor>b__23_0(Object state)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
at System.Threading.TimerQueue.FireNextTimers()
at System.Threading.TimerQueue.AppDomainTimerCallback(Int32 id)
```

**Comment by exileDev** [comment]
I can't reproduce. Closed #5656
