### ISSUE TITLE
Scheduled task to send emails - connection timed out

### ISSUE THREAD

**Issue by zombiegh0st** [nopSolutions/nopCommerce#5811]
**nopCommerce version:** 
4.40.3 

In docker env behind NginX Proxy Manager.
NginX config is pretty simple. Just a proxy-host with let's encrypt ssl and a "www" redirection host also with let's encrypt ssl.

**Steps to reproduce the problem:** 
Not sure if possible but here is what I did.
- fresh installation
- configure ssl
- configure email (test mail works)
- write a mail through contact form

Now scheduler cannot send the email. 
All other things work fine. Even with SSL there are no issues.

**Logging (original):**

> Die geplante Aufgabe "Send emails" schlug fehl mit dem Fehler "Operation timed out (asdf.com:443)" (Aufgabentyp: "Nop.Services.Messages.QueuedMessagesSendTask, Nop.Services", Shopname: "ASDF", Task-Ausführungsadresse: "https://asdf.com/scheduletask/runtask").

**Means in english something like:**

> The scheduled task "send email" failed due to "Operation timed out (asdf.com:443)" (Schedule type: "Nop.Services.Messages.QueuedMessagesSendTask, Nop.Services", Shopname: "ASDF", Task execute address: "https://asdf.com/scheduletask/runtask").

**Full message:**

```
System.Net.Http.HttpRequestException: Operation timed out (asdf.com:443)
---> System.Net.Sockets.SocketException (110): Operation timed out
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Nop.Services.Tasks.TaskThread.RunAsync() in /src/Libraries/Nop.Services/Tasks/TaskThread.cs:line 73
```

Also I am able to ping the public hostname from inside of the docker container.

**Comment by zombiegh0st** [comment]
Ok I've solved the issue. The problem was the firewall on the host. Almost everything is denied. Also the outgoing (public) communication from nopCommerce docker container. NopCommerce tried to reach asdf.com:443. That was the outgoing connection which was blocked. After adding the right rule, the issue was solved.

**Comment by glhays** [comment]
So was not a nopcommerce github issue?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by zombiegh0st** [comment]
Nope

**Comment by glhays** [comment]
Thanks, I track nop issues in my own repository base for future upgrades on my own site. So I will flag yours as SBOFNG.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
