### ISSUE TITLE
nop_commerce_web failed to start

### ISSUE THREAD

**Issue by diamonholdings** [nopSolutions/nopCommerce#5925]
Hi all,

nopCommerce version: 
branch: develop
Steps to reproduce the problem: 

I did run:
`docker-compose up -d`

and I obtained two running containers. The DB container works well, while the main application container shuts itself off after few seconds returning error 139 in Docker.
The error output I get is the following:

> Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Nop.Data.DataSettingsManager.LoadDataSettingsFromOldJsonFile(String data) in /src/Libraries/Nop.Data/DataSettingsManager.cs:line 83
   at Nop.Data.DataSettingsManager.LoadSettings(INopFileProvider fileProvider) in /src/Libraries/Nop.Data/DataSettingsManager.cs:line 113
   at Nop.Data.DataSettingsManager.IsDatabaseInstalled() in /src/Libraries/Nop.Data/DataSettingsManager.cs:line 146
   at Nop.Web.Framework.Infrastructure.Extensions.ServiceCollectionExtensions.AddThemes(IServiceCollection services) in /src/Presentation/Nop.Web.Framework/Infrastructure/Extensions/ServiceCollectionExtensions.cs:line 135
   at Nop.Web.Framework.Infrastructure.NopCommonStartup.ConfigureServices(IServiceCollection services, IConfiguration configuration) in /src/Presentation/Nop.Web.Framework/Infrastructure/NopCommonStartup.cs:line 41
   at Nop.Core.Infrastructure.NopEngine.ConfigureServices(IServiceCollection services, IConfiguration configuration) in /src/Libraries/Nop.Core/Infrastructure/NopEngine.cs:line 152
   at Nop.Web.Framework.Infrastructure.Extensions.ServiceCollectionExtensions.ConfigureApplicationServices(IServiceCollection services, IConfiguration configuration, IWebHostEnvironment webHostEnvironment) in /src/Presentation/Nop.Web.Framework/Infrastructure/Extensions/ServiceCollectionExtensions.cs:line 84
   at Nop.Web.Startup.ConfigureServices(IServiceCollection services) in /src/Presentation/Nop.Web/Startup.cs:line 37
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
  at Nop.Web.Program.Main(String[] args) in /src/Presentation/Nop.Web/Program.cs:line 15
   at Nop.Web.Program.<Main>(String[] args)
ln: /lib/ld-linux-x86-64.so.2: File exists
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Nop.Data.DataSettingsManager.LoadDataSettingsFromOldJsonFile(String data) in /src/Libraries/Nop.Data/DataSettingsManager.cs:line 83
   at Nop.Data.DataSettingsManager.LoadSettings(INopFileProvider fileProvider) in /src/Libraries/Nop.Data/DataSettingsManager.cs:line 113
   at Nop.Data.DataSettingsManager.IsDatabaseInstalled() in /src/Libraries/Nop.Data/DataSettingsManager.cs:line 146
   at Nop.Web.Framework.Infrastructure.Extensions.ServiceCollectionExtensions.AddThemes(IServiceCollection services) in /src/Presentation/Nop.Web.Framework/Infrastructure/Extensions/ServiceCollectionExtensions.cs:line 135
   at Nop.Web.Framework.Infrastructure.NopCommonStartup.ConfigureServices(IServiceCollection services, IConfiguration configuration) in /src/Presentation/Nop.Web.Framework/Infrastructure/NopCommonStartup.cs:line 41
   at Nop.Core.Infrastructure.NopEngine.ConfigureServices(IServiceCollection services, IConfiguration configuration) in /src/Libraries/Nop.Core/Infrastructure/NopEngine.cs:line 152
   at Nop.Web.Framework.Infrastructure.Extensions.ServiceCollectionExtensions.ConfigureApplicationServices(IServiceCollection services, IConfiguration configuration, IWebHostEnvironment webHostEnvironment) in /src/Presentation/Nop.Web.Framework/Infrastructure/Extensions/ServiceCollectionExtensions.cs:line 84
   at Nop.Web.Startup.ConfigureServices(IServiceCollection services) in /src/Presentation/Nop.Web/Startup.cs:line 37
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Nop.Web.Program.Main(String[] args) in /src/Presentation/Nop.Web/Program.cs:line 15
   at Nop.Web.Program.<Main>(String[] args)
ln: /lib/ld-linux-x86-64.so.2: File exists
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Nop.Data.DataSettingsManager.LoadDataSettingsFromOldJsonFile(String data) in /src/Libraries/Nop.Data/DataSettingsManager.cs:line 83
   at Nop.Data.DataSettingsManager.LoadSettings(INopFileProvider fileProvider) in /src/Libraries/Nop.Data/DataSettingsManager.cs:line 113
   at Nop.Data.DataSettingsManager.IsDatabaseInstalled() in /src/Libraries/Nop.Data/DataSettingsManager.cs:line 146
   at Nop.Web.Framework.Infrastructure.Extensions.ServiceCollectionExtensions.AddThemes(IServiceCollection services) in /src/Presentation/Nop.Web.Framework/Infrastructure/Extensions/ServiceCollectionExtensions.cs:line 135
   at Nop.Web.Framework.Infrastructure.NopCommonStartup.ConfigureServices(IServiceCollection services, IConfiguration configuration) in /src/Presentation/Nop.Web.Framework/Infrastructure/NopCommonStartup.cs:line 41
   at Nop.Core.Infrastructure.NopEngine.ConfigureServices(IServiceCollection services, IConfiguration configuration) in /src/Libraries/Nop.Core/Infrastructure/NopEngine.cs:line 152
   at Nop.Web.Framework.Infrastructure.Extensions.ServiceCollectionExtensions.ConfigureApplicationServices(IServiceCollection services, IConfiguration configuration, IWebHostEnvironment webHostEnvironment) in /src/Presentation/Nop.Web.Framework/Infrastructure/Extensions/ServiceCollectionExtensions.cs:line 84
   at Nop.Web.Startup.ConfigureServices(IServiceCollection services) in /src/Presentation/Nop.Web/Startup.cs:line 37
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Nop.Web.Program.Main(String[] args) in /src/Presentation/Nop.Web/Program.cs:line 15
   at Nop.Web.Program.<Main>(String[] args)
ln: /lib/ld-linux-x86-64.so.2: File exists
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Nop.Data.DataSettingsManager.LoadDataSettingsFromOldJsonFile(String data) in /src/Libraries/Nop.Data/DataSettingsManager.cs:line 83
   at Nop.Data.DataSettingsManager.LoadSettings(INopFileProvider fileProvider) in /src/Libraries/Nop.Data/DataSettingsManager.cs:line 113
   at Nop.Data.DataSettingsManager.IsDatabaseInstalled() in /src/Libraries/Nop.Data/DataSettingsManager.cs:line 146
   at Nop.Web.Framework.Infrastructure.Extensions.ServiceCollectionExtensions.AddThemes(IServiceCollection services) in /src/Presentation/Nop.Web.Framework/Infrastructure/Extensions/ServiceCollectionExtensions.cs:line 135
   at Nop.Web.Framework.Infrastructure.NopCommonStartup.ConfigureServices(IServiceCollection services, IConfiguration configuration) in /src/Presentation/Nop.Web.Framework/Infrastructure/NopCommonStartup.cs:line 41
   at Nop.Core.Infrastructure.NopEngine.ConfigureServices(IServiceCollection services, IConfiguration configuration) in /src/Libraries/Nop.Core/Infrastructure/NopEngine.cs:line 152
   at Nop.Web.Framework.Infrastructure.Extensions.ServiceCollectionExtensions.ConfigureApplicationServices(IServiceCollection services, IConfiguration configuration, IWebHostEnvironment webHostEnvironment) in /src/Presentation/Nop.Web.Framework/Infrastructure/Extensions/ServiceCollectionExtensions.cs:line 84
   at Nop.Web.Startup.ConfigureServices(IServiceCollection services) in /src/Presentation/Nop.Web/Startup.cs:line 37
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Nop.Web.Program.Main(String[] args) in /src/Presentation/Nop.Web/Program.cs:line 15
   at Nop.Web.Program.<Main>(String[] args)
ln: /lib/ld-linux-x86-64.so.2: File exists
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
  at Nop.Data.DataSettingsManager.LoadDataSettingsFromOldJsonFile(String data) in /src/Libraries/Nop.Data/DataSettingsManager.cs:line 83
   at Nop.Data.DataSettingsManager.LoadSettings(INopFileProvider fileProvider) in /src/Libraries/Nop.Data/DataSettingsManager.cs:line 113
   at Nop.Data.DataSettingsManager.IsDatabaseInstalled() in /src/Libraries/Nop.Data/DataSettingsManager.cs:line 146
   at Nop.Web.Framework.Infrastructure.Extensions.ServiceCollectionExtensions.AddThemes(IServiceCollection services) in /src/Presentation/Nop.Web.Framework/Infrastructure/Extensions/ServiceCollectionExtensions.cs:line 135
   at Nop.Web.Framework.Infrastructure.NopCommonStartup.ConfigureServices(IServiceCollection services, IConfiguration configuration) in /src/Presentation/Nop.Web.Framework/Infrastructure/NopCommonStartup.cs:line 41
   at Nop.Core.Infrastructure.NopEngine.ConfigureServices(IServiceCollection services, IConfiguration configuration) in /src/Libraries/Nop.Core/Infrastructure/NopEngine.cs:line 152
   at Nop.Web.Framework.Infrastructure.Extensions.ServiceCollectionExtensions.ConfigureApplicationServices(IServiceCollection services, IConfiguration configuration, IWebHostEnvironment webHostEnvironment) in /src/Presentation/Nop.Web.Framework/Infrastructure/Extensions/ServiceCollectionExtensions.cs:line 84
  at Nop.Web.Startup.ConfigureServices(IServiceCollection services) in /src/Presentation/Nop.Web/Startup.cs:line 37
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Nop.Web.Program.Main(String[] args) in /src/Presentation/Nop.Web/Program.cs:line 15
   at Nop.Web.Program.<Main>(String[] args)

**Comment by RomanovM** [comment]
@diamonholdings We don't recommend using Docker with develop branch since it's not tested. We'll do this and prepare instructions right before the release.

**Comment by diamonholdings** [comment]
Thank you Romanov,

I thought the module was ready and released as there is an ample guide in the website talking about the configuration:
[https://docs.nopcommerce.com/en/developer/tutorials/docker.html](url)
That guide is also pretty recent, March 2021.

I find Docker very handy for setting up the e-commerce as it can be done locally and deploy when ready.

1. **When is the team targeting this development?**

2. Also it would be nice to have a guideline to not just develop the website and SQL server containers, but also to upgrade subsequent changes of the website only while keeping the SQL intact.

**Comment by RomanovM** [comment]
It is ready, but not for the develop branch. You can use it for a stable release.

**Comment by diamonholdings** [comment]
ok, thanks.
I have pulled tag: release-4.40.4 and rerun docker-compose up -d that produced the following error: 

> docker-compose up -d
[+] Building 247.2s (34/59)
 => [internal] load build definition from Dockerfile                                                                                                                                                                 0.1s 
 => => transferring dockerfile: 3.46kB                                                                                                                                                                               0.0s 
 => [internal] load .dockerignore                                                                                                                                                                                    0.0s 
 => => transferring context: 3.61kB                                                                                                                                                                                  0.0s 
 => [internal] load metadata for mcr.microsoft.com/dotnet/aspnet:5.0-alpine                                                                                                                                          0.5s 
 => [internal] load metadata for mcr.microsoft.com/dotnet/sdk:5.0                                                                                                                                                    0.6s 
 => [runtime  1/10] FROM mcr.microsoft.com/dotnet/aspnet:5.0-alpine@sha256:9ad9fc297e526206b1d61aae8b025069b00bdf0c06d7b0507ce4dfe2fe5d00a0                                                                          0.0s 
 => [internal] load build context                                                                                                                                                                                    7.4s 
 => => transferring context: 195.60MB                                                                                                                                                                                7.3s 
 => [build  1/44] FROM mcr.microsoft.com/dotnet/sdk:5.0@sha256:1bd86365c0de18fb256bfe44e615c693d6be82cedc74a9a7cfb86164ec9514e9                                                                                      0.0s 
 => CACHED [runtime  2/10] RUN apk add --no-cache icu-libs                                                                                                                                                           0.0s 
 => CACHED [runtime  3/10] RUN apk add libgdiplus --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted                                                                         0.0s 
 => CACHED [runtime  4/10] RUN apk add libc-dev --no-cache                                                                                                                                                           0.0s 
 => CACHED [build  2/44] WORKDIR /src                                                                                                                                                                                0.0s 
 => [build  3/44] COPY ./src ./                                                                                                                                                                                      1.7s 
 => [runtime  5/10] COPY ./entrypoint.sh /entrypoint.sh                                                                                                                                                              0.5s 
 => [runtime  6/10] RUN chmod 755 /entrypoint.sh                                                                                                                                                                     0.6s 
 => [runtime  7/10] WORKDIR /app                                                                                                                                                                                     0.1s 
 => [runtime  8/10] RUN mkdir bin                                                                                                                                                                                    0.6s 
 => [build  4/44] RUN dotnet restore NopCommerce.sln                                                                                                                                                               138.2s 
 => [runtime  9/10] RUN mkdir logs                                                                                                                                                                                   0.7s 
 => [build  5/44] WORKDIR /src/Presentation/Nop.Web                                                                                                                                                                  0.0s 
 => [build  6/44] RUN dotnet build Nop.Web.csproj -c Release                                                                                                                                                        51.3s 
 => [build  7/44] WORKDIR /src/Plugins/Nop.Plugin.DiscountRules.CustomerRoles                                                                                                                                        0.0s 
 => [build  8/44] RUN dotnet build Nop.Plugin.DiscountRules.CustomerRoles.csproj -c Release                                                                                                                          8.3s 
 => [build  9/44] WORKDIR /src/Plugins/Nop.Plugin.ExchangeRate.EcbExchange                                                                                                                                           0.0s 
 => [build 10/44] RUN dotnet build Nop.Plugin.ExchangeRate.EcbExchange.csproj -c Release                                                                                                                             7.0s 
 => [build 11/44] WORKDIR /src/Plugins/Nop.Plugin.ExternalAuth.Facebook                                                                                                                                              0.0s 
 => [build 12/44] RUN dotnet build Nop.Plugin.ExternalAuth.Facebook.csproj -c Release                                                                                                                                7.9s 
 => [build 13/44] WORKDIR /src/Plugins/Nop.Plugin.Misc.Sendinblue                                                                                                                                                    0.0s 
 => [build 14/44] RUN dotnet build Nop.Plugin.Misc.Sendinblue.csproj -c Release                                                                                                                                      8.4s 
 => [build 15/44] WORKDIR /src/Plugins/Nop.Plugin.Payments.CheckMoneyOrder                                                                                                                                           0.0s 
 => [build 16/44] RUN dotnet build Nop.Plugin.Payments.CheckMoneyOrder.csproj -c Release                                                                                                                             7.4s 
 => [build 17/44] WORKDIR /src/Plugins/Nop.Plugin.Payments.Manual                                                                                                                                                    0.0s 
 => [build 18/44] RUN dotnet build Nop.Plugin.Payments.Manual.csproj -c Release                                                                                                                                      7.6s 
 => [build 19/44] WORKDIR /src/Plugins/Nop.Plugin.Payments.PayPalSmartPaymentButtons                                                                                                                                 0.0s 
 => ERROR [build 20/44] RUN dotnet build Nop.Plugin.Payments.PayPalSmartPaymentButtons.csproj -c Release                                                                                                             0.8s 
------
 > [build 20/44] RUN dotnet build Nop.Plugin.Payments.PayPalSmartPaymentButtons.csproj -c Release:
#34 0.761 Microsoft (R) Build Engine version 16.11.1+3e40a09f8 for .NET
#34 0.761 Copyright (C) Microsoft Corporation. All rights reserved.
#34 0.761
#34 0.763 MSBUILD : error MSB1009: Project file does not exist.
#34 0.763 Switch: Nop.Plugin.Payments.PayPalSmartPaymentButtons.csproj
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c dotnet build Nop.Plugin.Payments.PayPalSmartPaymentButtons.csproj -c Release]: exit code: 1

that was after pulling the image with
`docker pull nopcommerceteam/nopcommerce`

**Comment by skoshelev** [comment]
Hi @diamonholdings. The problem with PayPalSmartPaymentButtons plugin was fixed by [this commit](https://github.com/nopSolutions/nopCommerce/commit/5396449).

If you want to use docker image built yourself, you may use the 4.40-bug-fixes brunch.

Also, you may use our official docker image from [DockerHub](https://hub.docker.com/r/nopcommerceteam/nopcommerce/tags)

**Comment by skoshelev** [comment]
Closed #5925
