### ISSUE TITLE
Test failure: CanAddOrUpdateLocaleResource 

### ISSUE THREAD

**Issue by jhgbrt** [nopSolutions/nopCommerce#5959]
This test fails on my machine. I'm not qualified to diagnose ATM :-)

```
  Failed CanAddOrUpdateLocaleResource [86 ms]
  Error Message:
   Expected localeStringResources.Any() to be true, but found False.
  Stack Trace:
     at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Primitives.BooleanAssertions.BeTrue(String because, Object[] becauseArgs)
   at Nop.Tests.Nop.Services.Tests.Localization.LocalizationServiceTests.CanAddOrUpdateLocaleResource() in C:\Users\jeroe\source\repos\nopCommerce\src\Tests\Nop.Tests\Nop.Services.Tests\Localization\LocalizationServiceTests.cs:line 63
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
```

**Comment by skoshelev** [comment]
Fixed by https://github.com/nopSolutions/nopCommerce/commit/63753dcebed13217c9591b02e1716b372f707f40
