### ISSUE TITLE
upgrading a database from 4.3 to 4.5 directly does not work

### ISSUE THREAD

**Issue by skoshelev** [nopSolutions/nopCommerce#6098]
nopCommerce version: 4.50

Steps to reproduce the problem: 

I just tested upgrading a database from 4.3 to 4.5 directly (using the migrations provided by nopCommerce) but I got the following error:

```
Unhandled exception. System.AggregateException: One or more errors occurred. (The value '0' is not a valid value for the enum 'ShippingSortingEnum'.)
---> System.ArgumentException: The value '0' is not a valid value for the enum 'ShippingSortingEnum'.
   at System.ComponentModel.EnumConverter.ConvertTo(ITypeDescriptorContext context, CultureInfo culture, Object value, Type destinationType)
   at System.ComponentModel.TypeConverter.ConvertToString(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.ComponentModel.TypeConverter.ConvertToInvariantString(Object value)
   at Nop.Services.Configuration.SettingService.SetSettingAsync(Type type, String key, Object value, Int32 storeId, Boolean clearCache)
   at Nop.Services.Configuration.SettingService.SaveSettingAsync[T](T settings, Int32 storeId)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Nop.Web.Framework.Migrations.UpgradeTo440.SettingMigration.Up()
   at FluentMigrator.MigrationBase.GetUpExpressions(IMigrationContext context)
   at FluentMigrator.Runner.MigrationRunner.<>c.<ApplyMigrationUp>b__69_0(IMigration m, IMigrationContext c)
   at FluentMigrator.Runner.MigrationRunner.ExecuteMigration(IMigration migration, Action`2 getExpressions)
   at FluentMigrator.Runner.MigrationRunner.ApplyMigrationUp(IMigrationInfo migrationInfo, Boolean useTransaction)
   at FluentMigrator.Runner.MigrationRunner.Up(IMigration migration)
   at Nop.Data.Migrations.MigrationManager.ApplyUpMigrations(Assembly assembly, MigrationProcessType migrationProcessType)
   at Nop.Web.Framework.Infrastructure.Extensions.ApplicationBuilderExtensions.StartEngine(IApplicationBuilder application)
   at Program.<Main>$(String[] args)
```
See details on [this post](https://www.nopcommerce.com/en/boards/topic/92668/nopcommerce-450-suggestions-bug-reports-and-improvements/page/3#292230)

**Comment by skoshelev** [comment]
Closed #6098
