### ISSUE TITLE
Unhandled exception. System.Exception: Method 'Void' in type from assembly does not have an implementation.

### ISSUE THREAD

**Issue by adnanmasd** [nopSolutions/nopCommerce#6234]
nopCommerce version: 4.5.0

Steps to reproduce the problem: 

1. Upload payment processor plugin
2. Install payment processor plugin 
3. Restart the Application

I have made my custom payment process. The plugin is working fine on my local environment. Once I try to install it on my cloud testing environment, the application fails to start. The log shows the following:

```
Unhandled exception. System.Exception: Plugin 'URWAY - Redirect'. Method 'Void' in type 'Nop.Plugin.Payments.UrwayRedirect.UrwayRedirectPaymentProcessor' from assembly 'Nop.Plugin.Payments.UrwayRedirect, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

Unable to load one or more of the requested types.
Method 'Void' in type 'Nop.Plugin.Payments.UrwayRedirect.UrwayRedirectPaymentProcessor' from assembly 'Nop.Plugin.Payments.UrwayRedirect, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

 ---> System.Exception: Plugin 'URWAY - Redirect'. Method 'Void' in type 'Nop.Plugin.Payments.UrwayRedirect.UrwayRedirectPaymentProcessor' from assembly 'Nop.Plugin.Payments.UrwayRedirect, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

 ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'Void' in type 'Nop.Plugin.Payments.UrwayRedirect.UrwayRedirectPaymentProcessor' from assembly 'Nop.Plugin.Payments.UrwayRedirect, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Nop.Web.Framework.Infrastructure.Extensions.ApplicationPartManagerExtensions.InitializePlugins(ApplicationPartManager applicationPartManager, PluginConfig pluginConfig)
System.TypeLoadException: Method 'Void' in type 'Nop.Plugin.Payments.UrwayRedirect.UrwayRedirectPaymentProcessor' from assembly 'Nop.Plugin.Payments.UrwayRedirect, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   --- End of inner exception stack trace ---
   at Nop.Web.Framework.Infrastructure.Extensions.ApplicationPartManagerExtensions.InitializePlugins(ApplicationPartManager applicationPartManager, PluginConfig pluginConfig)
   --- End of inner exception stack trace ---
   at Nop.Web.Framework.Infrastructure.Extensions.ApplicationPartManagerExtensions.InitializePlugins(ApplicationPartManager applicationPartManager, PluginConfig pluginConfig)
   at Nop.Web.Framework.Infrastructure.Extensions.ServiceCollectionExtensions.ConfigureApplicationServices(IServiceCollection services, WebApplicationBuilder builder)
   at Program.<Main>$(String[] args)
```

Any Idea what could be the issue?

**Comment by RomanovM** [comment]
The problem is in the third-party plugin, contact its developer.

**Comment by adnanmasd** [comment]
@RomanovM, I am the developer of the plugin. The plugin is working fine in the local machine but crashes on cloud. 
Does anyone else faced similar issue?
