### ISSUE TITLE
WebOptimizer - Collection was modified; enumeration operation may not execute

### ISSUE THREAD

**Issue by kiranbhadani** [nopSolutions/nopCommerce#6366]
nopCommerce version: 4.50.3

Steps to reproduce the problem: It randomly happens in production environment

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at WebOptimizer.Asset.ExpandGlobs(IAsset asset, IWebHostEnvironment env)
   at WebOptimizer.Asset.GenerateCacheKey(HttpContext context)
   at Nop.Web.Framework.UI.NopHtmlHelper.GenerateScripts(ResourceLocation location) in E:\Retailhub\Source\Devel4.5\Presentation\Nop.Web.Framework\UI\NopHtmlHelper.cs:line 369
   at AspNetCore._Themes_Brooklyn_Views_Shared__Root_Head.<>c__DisplayClass10_0.<<ExecuteAsync>b__1>d.MoveNext() in C:\inetpub\wwwroot\Retailhub45\Themes\Brooklyn\Views\Shared\_Root.Head.cshtml:line 82
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
   at AspNetCore._Themes_Brooklyn_Views_Shared__Root_Head.ExecuteAsync() in C:\inetpub\wwwroot\Retailhub45\Themes\Brooklyn\Views\Shared\_Root.Head.cshtml:line 75
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)

**Comment by exileDev** [comment]
Moved to #6333. Still couldn't reproduce

**Comment by kiranbhadani** [comment]
@exileDev It's reproducible in case of concurrent users and page has some dynamic css/scripts added, for example if I have some store wise custom css files, some stores can have that and other store can not, so that bundle file for home page for one store will have x no of source files where as y no of source files for other store, and when you hit home page url of both stores at the same time

**Comment by kiranbhadani** [comment]
@exileDev Can you pls re-open this and it's different from #6333, I am able to fix it by changing bundle names as it was in v4.3

**Comment by exileDev** [comment]
@kiranbhadani I hope this helps. Besides it should reduce the number of cache files.

Closed #6366

**Comment by kiranbhadani** [comment]
@exileDev Looks good
