### ISSUE TITLE
Deleted discount code breaks order details in admin

### ISSUE THREAD

**Issue by chrisjainsley** [nopSolutions/nopCommerce#6463]
**nopCommerce version:** 4.50.3

**Steps to reproduce the problem:** 
Given I have a discount applied to an existing order
When I delete the discount
And view the order in admin (/Admin/Order/Edit/4450)
Then I receive an error 500

**Error:**

It appears it is getting the discount code on line 532 (OrderModelFactory) and expects to always be there.

````
System.NullReferenceException: Object reference not set to an instance of an object.
   at Nop.Web.Areas.Admin.Factories.OrderModelFactory.PrepareOrderModelTotalsAsync(OrderModel model, Order order) in C:\Repos\intelligentservers\src\Presentation\Nop.Web\Areas\Admin\Factories\OrderModelFactory.cs:line 534
   at Nop.Web.Areas.Admin.Factories.OrderModelFactory.PrepareOrderModelAsync(OrderModel model, Order order, Boolean excludeProperties) in C:\Repos\intelligentservers\src\Presentation\Nop.Web\Areas\Admin\Factories\OrderModelFactory.cs:line 1202
   at Nop.Web.Areas.Admin.Controllers.OrderController.Edit(Int32 id) in C:\Repos\intelligentservers\src\Presentation\Nop.Web\Areas\Admin\Controllers\OrderController.cs:line 877
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Nop.Services.Authentication.AuthenticationMiddleware.InvokeAsync(HttpContext context) in C:\Repos\intelligentservers\src\Libraries\Nop.Services\Authentication\AuthenticationMiddleware.cs:line 94
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 121
   at WebMarkupMin.AspNetCore6.WebMarkupMinMiddlewareBase.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Nop.Services.Installation.InstallUrlMiddleware.InvokeAsync(HttpContext context, IWebHelper webHelper) in C:\Repos\intelligentservers\src\Libraries\Nop.Services\Installation\InstallUrlMiddleware.cs:line 52
   at Nop.Services.Common.KeepAliveMiddleware.InvokeAsync(HttpContext context, IWebHelper webHelper) in C:\Repos\intelligentservers\src\Libraries\Nop.Services\Common\KeepAliveMiddleware.cs:line 49
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by brandonjamesparkinson** [comment]
Would an appropriate solution be to keep that discount in but reduce its value to 0% so it can't be used, and show a prompt to the user 'discount unavailable' rather than fully remove it?

**Comment by chrisjainsley** [comment]
> Would an appropriate solution be to keep that discount in but reduce its value to 0% so it can't be used, and show a prompt to the user 'discount unavailable' rather than fully remove it?

To keep the client happy I readded the discount and set the dates to expired, this means the discount is no longer avalaible.

**Comment by AndreiMaz** [comment]
@chrisjainsley I cannot reproduce the issue. When a discount is deleted, an appropriate "DiscountUsageHistory" is also deleted. So no exception could be thrown. Could you please set a breakpoint in this method and check whether exactly the exception is thrown?

@brandonjamesparkinson We've added "Is active" property to discount in version 4.60

**Comment by AndreiMaz** [comment]
@chrisjainsley I cannot reproduce the issue. When a discount is deleted, an appropriate "DiscountUsageHistory" is also deleted. So no exception could be thrown.

@brandonjamesparkinson We've added "Is active" property to discount in version 4.60
