### ISSUE TITLE
SQL Deadlocks during order creation

### ISSUE THREAD

**Issue by skoshelev** [nopSolutions/nopCommerce#6482]
nopCommerce version: 4.50+

On a relatively busy site (60-100 orders/day), we are getting 2-3 deadlocks per day, all on URL https://...../checkout/confirm and the result is that the payment has been taken on the gateway, but the order receipt not emailed and the order left in "Pending" state and payment state is "Paid" with one of the payment methods, or "Pending" with the other two - not the expected "Processing" (NB. with one of the payment methods the payment is not taken so we sometimes lose a sale if the customer doesn't try again).

The NOP admin log has the following each time the issue occurs:

```
Microsoft.Data.SqlClient.SqlException (0x80131904): Transaction (Process ID 146) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at LinqToDB.Data.DataConnection.ExecuteNonQueryAsync(CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQueryAsync(CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.NonQueryQueryAsync(Query query, IDataContext dataContext, Expression expression, Object[] ps, Object[] preambles, CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.NonQueryQueryAsync(Query query, IDataContext dataContext, Expression expression, Object[] ps, Object[] preambles, CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.Delete`1.QueryAsync(IDataContext dataContext, T obj, String tableName, String serverName, String databaseName, String schemaName, TableOptions tableOptions, CancellationToken token)
   at Nop.Data.DataProviders.BaseDataProvider.DeleteEntityAsync[TEntity](TEntity entity) in D:\inetpub\wwwroot\NOP4-50-4\Libraries\Nop.Data\DataProviders\BaseDataProvider.cs:line 335
   at Nop.Data.EntityRepository`1.DeleteAsync(TEntity entity, Boolean publishEvent) in D:\inetpub\wwwroot\NOP4-50-4\Libraries\Nop.Data\EntityRepository.cs:line 457
   at Nop.Services.Common.GenericAttributeService.DeleteAttributeAsync(GenericAttribute attribute) in D:\inetpub\wwwroot\NOP4-50-4\Libraries\Nop.Services\Common\GenericAttributeService.cs:line 45
   at Nop.Services.Common.GenericAttributeService.SaveAttributeAsync[TPropType](BaseEntity entity, String key, TPropType value, Int32 storeId) in D:\inetpub\wwwroot\NOP4-50-4\Libraries\Nop.Services\Common\GenericAttributeService.cs:line 165
   at Nop.Services.Customers.CustomerService.ResetCheckoutDataAsync(Customer customer, Int32 storeId, Boolean clearCouponCodes, Boolean clearCheckoutAttributes, Boolean clearRewardPoints, Boolean clearShippingMethod, Boolean clearPaymentMethod) in D:\inetpub\wwwroot\NOP4-50-4\Libraries\Nop.Services\Customers\CustomerService.cs:line 716
   at Nop.Services.Orders.OrderProcessingService.PlaceOrderAsync(ProcessPaymentRequest processPaymentRequest) in D:\inetpub\wwwroot\NOP4-50-4\Libraries\Nop.Services\Orders\OrderProcessingService.cs:line 1668
ClientConnectionId:b6e67fbb-228d-4e51-8e59-87e518c7e46f
Error Number:1205,State:51,Class:13
```

see details on [this post](https://www.nopcommerce.com/en/boards/topic/95774/sql-deadlocks-during-order-creation#302107)

**Comment by skoshelev** [comment]
I could not even find a theoretical possibility to repeat this problem

Closed #6482

**Comment by MehdiNaz** [comment]
We have exactly the same problem

**Comment by kava81** [comment]
we too. not very frequent but we have this problem
1 site in 4.0 and 1 in 4.5

**Comment by szocco** [comment]
We have experienced deadlocks as well using 4.30
System.Data.SqlClient.SqlException (0x80131904): Transaction (Process ID 97) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)

**Comment by MehdiNaz** [comment]
I am getting the same error

**Comment by untiedshoes** [comment]
Just so you're aware, we've had two of these today too. Currently sitting at 900 orders for the day, with two 'Transaction (Process ID ) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.'

**Comment by untiedshoes** [comment]
[https://www.mssqltips.com/sqlservertip/2517/using-a-clustered-index-to-solve-a-sql-server-deadlock-issue/](url)
