### ISSUE TITLE
Redis Cache Error

### ISSUE THREAD

**Issue by streamzyuk** [nopSolutions/nopCommerce#6570]
nopCommerce version: 4.7 Dev

Steps to reproduce the problem: 
Create a redis cluster (free version)

Set Distributed Cache App Settings

Run the App.

I get this error

One or more errors occurred. (Multi-key operations must involve a single slot; keys can use 'hash tags' to help this, i.e. '{/users/12345}/account' and '{/users/12345}/contacts' will always be in the same slot)

It looks like we need hash tags for new improvements to work. Or am I doing something wrong?

**Comment by streamzyuk** [comment]
This error does not always occurs. It happens when removing multiple keys which are distributed on different shards.

**Comment by streamzyuk** [comment]
Here is the exception log

StackExchange.Redis.RedisCommandException: Multi-key operations must involve a single slot; keys can use 'hash tags' to help this, i.e. '{/users/12345}/account' and '{/users/12345}/contacts' will always be in the same slot
   at StackExchange.Redis.ConnectionMultiplexer.PrepareToPushMessageToBridge[T](Message message, ResultProcessor`1 processor, IResultBox`1 resultBox, ServerEndPoint& server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2198
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2817
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/RedisBase.cs:line 54
   at StackExchange.Redis.RedisDatabase.KeyDelete(RedisKey[] keys, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 614
   at Nop.Services.Caching.RedisCacheManager.RemoveByPrefixAsync(String prefix, Object[] prefixParameters) in C:\Streamzy\Source29122022\src\Libraries\Nop.Services\Caching\RedisCacheManager.cs:line 69
   at Nop.Services.Catalog.ProductTagService.UpdateProductTagsAsync(Product product, String[] productTags) in C:\Streamzy\Source29122022\src\Libraries\Nop.Services\Catalog\ProductTagService.cs:line 370
   at Nop.Web.Areas.Admin.Controllers.ProductController.Create(ProductModel model, Boolean continueEditing) in C:\Streamzy\Source29122022\src\Presentation\Nop.Web\Areas\Admin\Controllers\ProductController.cs:line 888
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Nop.Services.Authentication.AuthenticationMiddleware.InvokeAsync(HttpContext context) in C:\Streamzy\Source29122022\src\Libraries\Nop.Services\Authentication\AuthenticationMiddleware.cs:line 94
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 121
   at WebMarkupMin.AspNetCore7.WebMarkupMinMiddleware.InvokeCore(HttpContext context, Boolean useMinification, Boolean useCompression)
   at WebMarkupMin.AspNetCore7.WebMarkupMinMiddleware.InvokeCore(HttpContext context, Boolean useMinification, Boolean useCompression)
   at NWebsec.AspNetCore.Middleware.Middleware.CspMiddleware.Invoke(HttpContext context)
   at Nop.Web.Framework.Infrastructure.Extensions.ApplicationBuilderStrmzyExtensions.<>c.<<UseSecurityHeaders>b__0_3>d.MoveNext() in C:\Streamzy\Source29122022\src\Presentation\Nop.Web.Framework\Strmzy\Infrastructure\Extensions\ApplicationBuilderStrmzyExtensions.cs:line 39
--- End of stack trace from previous location ---
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Nop.Services.Installation.InstallUrlMiddleware.InvokeAsync(HttpContext context, IWebHelper webHelper) in C:\Streamzy\Source29122022\src\Libraries\Nop.Services\Installation\InstallUrlMiddleware.cs:line 52
   at Nop.Services.Common.KeepAliveMiddleware.InvokeAsync(HttpContext context, IWebHelper webHelper) in C:\Streamzy\Source29122022\src\Libraries\Nop.Services\Common\KeepAliveMiddleware.cs:line 49
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|8_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)

**Comment by skoshelev** [comment]
Hi, @streamzyuk. I have analyzed the problem. Indeed, the current implementation without improvements will not work in a cluster of redis servers. However, we do not see the need to include such changes in the core and have decided to leave this for customizations.

**Comment by streamzyuk** [comment]
Hi I will try to analyze and try to implement it. But redis cluster is at the core of redis. That should be considered.
Previous versions were working on clusters without any issues

**Comment by streamzyuk** [comment]
I have updated the CacheKey Class Create function as below, and changed the RedisCacheManager with the following code.
Now it works without error with Redis Cluster Mode. And the distribution of keys to nodes looks even.

        public virtual CacheKey Create(Func<object, object> createCacheKeyParameters, params object[] keyObjects)
        {
            

            if (!keyObjects.Any())
            {
                if (Prefixes.Any())
                {
                    var shortestPrefix = Prefixes?.MinBy(p => p.Length);

                    var hastagedPrefixes = Prefixes.Select(p => p.Replace(shortestPrefix, $"{{{shortestPrefix}}}"));

                    var hastagedKey = Key.Replace(shortestPrefix, $"{{{shortestPrefix}}}");

                    var cacheKey = new CacheKey(hastagedKey, hastagedPrefixes.ToArray());

                    return cacheKey;
                }
                else
                {
                    var cacheKey = new CacheKey(Key, Prefixes.ToArray());

                    return cacheKey;

                }
                
            }
            else
            {
                if (Prefixes.Any())
                {
                    var shortestPrefix = Prefixes.MinBy(p => p.Length);

                    var hastagedPrefixes = Prefixes.Select(p => p.Replace(shortestPrefix, $"{{{{{shortestPrefix}}}}}"));

                    var hastagedKey = Key.Replace(shortestPrefix, $"{{{{{shortestPrefix}}}}}");

                    var cacheKey = new CacheKey(hastagedKey, hastagedPrefixes.ToArray());

                    for (var i = 0; i < cacheKey.Prefixes.Count; i++)
                        cacheKey.Prefixes[i] = string.Format(cacheKey.Prefixes[i], keyObjects.Select(createCacheKeyParameters).ToArray());

                    cacheKey.Key = string.Format(cacheKey.Key, keyObjects.Select(createCacheKeyParameters).ToArray());

                    return cacheKey;
                }
                else
                {
                    var cacheKey = new CacheKey(Key, Prefixes.ToArray());

                    cacheKey.Key = string.Format(cacheKey.Key, keyObjects.Select(createCacheKeyParameters).ToArray());

                    for (var i = 0; i < cacheKey.Prefixes.Count; i++)
                        cacheKey.Prefixes[i] = string.Format(cacheKey.Prefixes[i], keyObjects.Select(createCacheKeyParameters).ToArray());

                    return cacheKey;
                }
                
            }
  
        }


RedisCacheManager.cs Override the following method.

protected override string PrepareKeyPrefix(string prefix, params object[] prefixParameters)
        {
            return prefixParameters?.Any() ?? false
                ? $"{{{string.Format(prefix, prefixParameters.Select(CreateCacheKeyParameters).ToArray())}}}"
                : $"{{{prefix}}}";
        }
