### ISSUE TITLE
Caching Bug

### ISSUE THREAD

**Issue by streamzyuk** [nopSolutions/nopCommerce#6597]
nopCommerce version: Latest Dev

Steps to reproduce the problem: Install and run the app. Navigate back and forth to some categories and products.

Just installed the latest dev version. No settings altered.  As installed

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Nop.Core
  StackTrace:
   at Nop.Core.Caching.MemoryCacheManager.RemoveByPrefixAsync(String prefix, Object[] prefixParameters) in C:\Streamzy\Working Source\src\Libraries\Nop.Core\Caching\MemoryCacheManager.cs:line 189
   at Nop.Web.Infrastructure.Cache.ModelCacheEventConsumer.<HandleEventAsync>d__32.MoveNext() in C:\Streamzy\Working Source\src\Presentation\Nop.Web\Infrastructure\Cache\ModelCacheEventConsumer.cs:line 394
   at Nop.Services.Events.EventPublisher.<PublishAsync>d__0`1.MoveNext() in C:\Streamzy\Working Source\src\Libraries\Nop.Services\Events\EventPublisher.cs:line 33

  This exception was originally thrown at this call stack:
    Nop.Core.Caching.MemoryCacheManager.RemoveByPrefixAsync(string, object[]) in MemoryCacheManager.cs
    Nop.Web.Infrastructure.Cache.ModelCacheEventConsumer.HandleEventAsync(Nop.Core.Events.EntityUpdatedEvent<Nop.Core.Domain.Media.Picture>) in ModelCacheEventConsumer.cs
    Nop.Services.Events.EventPublisher.PublishAsync<TEvent>(TEvent) in EventPublisher.cs

**Comment by AndreiMaz** [comment]
Also experiencing it after a clean installation during the first website start. Although you can see it when debuging ("PublishAsync" method) but anyway a developer can see an exception

**Comment by skoshelev** [comment]
Closed #6597
