### ISSUE TITLE
IO Exception after changing storage for images

### ISSUE THREAD

**Issue by exileDev** [nopSolutions/nopCommerce#6602]
nopCommerce version: develop

Steps to reproduce the problem: 

>I have Nopcommerce installed with pictures stored in database. After that I changed to file system and I got error when I first open any product. It looks like many processes try to create/update same file image.

```
System.IO.IOException: The process cannot access the file 'C:\Users\SSM\source\Workspaces\NopCommerce\nopCommerce461\src\Presentation\Nop.Web\wwwroot\images\0000036_0.jpeg' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.<WriteAllBytesAsync>g__Core|92_0(String path, Byte[] bytes, CancellationToken cancellationToken)
   at Nop.Core.Infrastructure.NopFileProvider.WriteAllBytesAsync(String filePath, Byte[] bytes) in C:\Users\SSM\source\Workspaces\NopCommerce\nopCommerce461\src\Libraries\Nop.Core\Infrastructure\NopFileProvider.cs:line 566
   at Nop.Services.Media.PictureService.SavePictureInFileAsync(Int32 pictureId, Byte[] pictureBinary, String mimeType) in C:\Users\SSM\source\Workspaces\NopCommerce\nopCommerce461\src\Libraries\Nop.Services\Media\PictureService.cs:line 108
...
```

Source: https://www.nopcommerce.com/en/boards/topic/96287/media-file-system

**Comment by exileDev** [comment]
Closed #6602
