### ISSUE TITLE
Delete guests task timeout every time it is run

### ISSUE THREAD

**Issue by danFbach** [nopSolutions/nopCommerce#6668]
nopCommerce version: 4.6.2

Steps to reproduce the problem: Allow the Delete guests task to run, or run it manually.

I have been having this issue since I installed 4.6. Every time the Delete guests task is run i get the error:
`The Command Timeout expired before the operation completed.`
And no guests are actually deleted.
After reviewing my database, I have approximately 500,000 guest accounts, where Email is null.
It was brought to my attention today because there was a DDOS-like attack on my server that created another ~100k guest accounts and I would like to delete them.
Is there any negative consequences (other than maybe deleting some valid guests) of just running a SQL command like the following?
```sql
DELETE FROM Customers WHERE Email IS NULL AND CreatedOnUtc < 'Some date i determine';
```

**Comment by danFbach** [comment]
Here is the stack trace.
```
MySqlConnector.MySqlException (0x80004005): The Command Timeout expired before the operation completed.
---> MySqlConnector.MySqlException (0x80004005): Query execution was interrupted
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 175
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 133
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 493
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 77
   at MySqlConnector.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 304
   at MySqlConnector.MySqlCommand.ExecuteNonQuery() in /_/src/MySqlConnector/MySqlCommand.cs:line 107
   at LinqToDB.Data.DataConnection.ExecuteNonQuery(DbCommand command)
   at LinqToDB.Data.DataConnection.ExecuteNonQuery()
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQueryImpl(DataConnection dataConnection, ExecutionPreparedQuery executionQuery)
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQuery()
   at LinqToDB.DataContext.QueryRunner.ExecuteNonQuery()
   at LinqToDB.Linq.QueryRunner.NonQueryQuery(Query query, IDataContext dataContext, Expression expr, Object[] parameters, Object[] preambles)
   at LinqToDB.Linq.QueryRunner.<>c__DisplayClass31_0.<SetNonQueryQuery>b__0(IDataContext db, Expression expr, Object[] ps, Object[] preambles)
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at LinqToDB.LinqExtensions.Insert[TSource,TTarget](IQueryable`1 source, ITable`1 target, Expression`1 setter)
   at LinqToDB.TempTable`1.Insert(IQueryable`1 items)
   at LinqToDB.TempTable`1..ctor(IDataContext db, IQueryable`1 items, String tableName, String databaseName, String schemaName, Action`1 action, String serverName, TableOptions tableOptions)
   at LinqToDB.TempTable`1..ctor(IDataContext db, String tableName, IQueryable`1 items, String databaseName, String schemaName, Action`1 action, String serverName, TableOptions tableOptions)
   at Nop.Data.TempSqlDataStorage`1..ctor(String storageName, IQueryable`1 query, IDataContext dataConnection) in C:\VSProjects\nopcom46\src\Libraries\Nop.Data\TempSqlDataStorage.cs:line 16
   at Nop.Data.DataProviders.BaseDataProvider.CreateTempDataStorageAsync[TItem](String storeKey, IQueryable`1 query) in C:\VSProjects\nopcom46\src\Libraries\Nop.Data\DataProviders\BaseDataProvider.cs:line 162
   at Nop.Services.Customers.CustomerService.DeleteGuestCustomersAsync(Nullable`1 createdFromUtc, Nullable`1 createdToUtc, Boolean onlyWithoutShoppingCart) in C:\VSProjects\nopcom46\src\Libraries\Nop.Services\Customers\CustomerService.cs:line 699
   at Nop.Services.Customers.CustomerService.DeleteGuestCustomersAsync(Nullable`1 createdFromUtc, Nullable`1 createdToUtc, Boolean onlyWithoutShoppingCart) in C:\VSProjects\nopcom46\src\Libraries\Nop.Services\Customers\CustomerService.cs:line 713
   at Nop.Services.Customers.DeleteGuestsTask.ExecuteAsync() in C:\VSProjects\nopcom46\src\Libraries\Nop.Services\Customers\DeleteGuestsTask.cs:line 41
   at Nop.Services.ScheduleTasks.ScheduleTaskRunner.PerformTaskAsync(ScheduleTask scheduleTask) in C:\VSProjects\nopcom46\src\Libraries\Nop.Services\ScheduleTasks\ScheduleTaskRunner.cs:line 83
   at Nop.Core.Caching.MemoryCacheManager.PerformActionWithLockAsync(String resource, TimeSpan expirationTime, Func`1 action) in C:\VSProjects\nopcom46\src\Libraries\Nop.Core\Caching\MemoryCacheManager.cs:line 262
   at Nop.Services.ScheduleTasks.ScheduleTaskRunner.ExecuteAsync(ScheduleTask scheduleTask, Boolean forceRun, Boolean throwException, Boolean ensureRunOncePerPeriod) in C:\VSProjects\nopcom46\src\Libraries\Nop.Services\ScheduleTasks\ScheduleTaskRunner.cs:line 166
   at Nop.Services.ScheduleTasks.ScheduleTaskRunner.ExecuteAsync(ScheduleTask scheduleTask, Boolean forceRun, Boolean throwException, Boolean ensureRunOncePerPeriod) in C:\VSProjects\nopcom46\src\Libraries\Nop.Services\ScheduleTasks\ScheduleTaskRunner.cs:line 166
   at Nop.Web.Areas.Admin.Controllers.ScheduleTaskController.RunNow(Int32 id) in C:\VSProjects\nopcom46\src\Presentation\Nop.Web\Areas\Admin\Controllers\ScheduleTaskController.cs:line 128
```

**Comment by danFbach** [comment]
Increasing the DefaultCommandTimeout on the db connection allowed it to run longer, but this time i hit the nginx time out and then hit the command timeout again (I set it to 600 seconds, 10 minutes.) 
There are 555k users with a NULL email.
I realize that this is an edge case, considering i have so many guest accounts, but perhaps the task query shouldn't try to do it all at once and instead process them in groups?...

looking at the slow query log
```
# Time: 230411 18:25:10
# User@Host: ***[***] @ localhost [::1]
# Thread_id: 22891  Schema: ***_nop  QC_hit: No
# Query_time: 30.009293  Lock_time: 0.000431  Rows_sent: 0  Rows_examined: 59067172
# Rows_affected: 0  Bytes_sent: 44
SET timestamp=1681237510;
```
Almost 60 million rows were examined when this is run

```sql
INSERT INTO `tmp_guestsAddressesToDelete`
(
        `AddressId`
)
SELECT
        `ca`.`Address_Id`
FROM
        `CustomerAddresses` `ca`
WHERE
        EXISTS(
                SELECT
                        *
                FROM
                        `tmp_guestsToDelete` `c_1`
                WHERE
                        `c_1`.`CustomerId` = `ca`.`Customer_Id`
        );
```

**Comment by danFbach** [comment]
On this attempt, with timeout set to 600, it examined 1.2 billion records... perhaps there is a recursion issue here...?
```
# Time: 230411 19:00:16
# User@Host: leecom_nopcom[leecom_nopcom] @ localhost [::1]
# Thread_id: 23238  Schema: leecom_nop  QC_hit: No
# Query_time: 600.013014  Lock_time: 0.000456  Rows_sent: 0  Rows_examined: 1217755653
# Rows_affected: 0  Bytes_sent: 44
```
```sql
SET timestamp=1681239616;
INSERT INTO `tmp_guestsAddressesToDelete`
(
        `AddressId`
)
SELECT
        `ca`.`Address_Id`
FROM
        `CustomerAddresses` `ca`
WHERE
        EXISTS(
                SELECT
                        *
                FROM
                        `tmp_guestsToDelete` `c_1`
                WHERE
                        `c_1`.`CustomerId` = `ca`.`Customer_Id`
        );
```

**Comment by AndreiMaz** [comment]
We use GitHub for work items only. Please post all questions on [nopCommerce forums](https://www.nopcommerce.com/en/boards)
