### ISSUE TITLE
RedisTimeoutException: Timeout performing SCAN

### ISSUE THREAD

**Issue by kucukemre** [nopSolutions/nopCommerce#6683]
nopCommerce version: 4.60.2

I'm getting this error and similar;

StackExchange.Redis.RedisTimeoutException: Timeout performing SCAN (15000ms), next: SCAN, inst: 912, qu: 0, qs: 216, aw: False, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, serverEndpoint: 172.31.0.30:6379, mc: 1/1/0, mgr: 8 of 10 available, clientName: VM49784, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=226,Free=32541,Min=8,Max=32767), v: 2.2.4.27433 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.CursorEnumerable`1.Enumerator.ThrowTimeout(Message message) in /_/src/StackExchange.Redis/CursorEnumerable.cs:line 249
   at StackExchange.Redis.CursorEnumerable`1.Enumerator.SlowNextSync() in /_/src/StackExchange.Redis/CursorEnumerable.cs:line 192
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at Nop.Services.Caching.RedisCacheManager.RemoveByPrefixAsync(String prefix, Object[] prefixParameters) in C:\agent\_work\2\s\Libraries\Nop.Services\Caching\RedisCacheManager.cs:line 76
   at Nop.Services.Caching.CacheEventConsumer`1.RemoveByPrefixAsync(String prefix, Object[] prefixParameters) in C:\agent\_work\2\s\Libraries\Nop.Services\Caching\CacheEventConsumer.cs:line 73
   at Nop.Services.Caching.CacheEventConsumer`1.ClearCacheAsync(TEntity entity, EntityEventType entityEventType) in C:\agent\_work\2\s\Libraries\Nop.Services\Caching\CacheEventConsumer.cs:line 52
   at Nop.Services.Caching.CacheEventConsumer`1.HandleEventAsync(EntityInsertedEvent`1 eventMessage) in C:\agent\_work\2\s\Libraries\Nop.Services\Caching\CacheEventConsumer.cs:line 98
   at Nop.Services.Events.EventPublisher.PublishAsync[TEvent](TEvent event) in C:\agent\_work\2\s\Libraries\Nop.Services\Events\EventPublisher.cs:line 52

My connection string is so: "IP:PORT,connectTimeout=15000,ssl=False,user=username,password=password,allowAdmin=true,syncTimeout=15000"

Am I doing something wrong?

**Comment by AndreiMaz** [comment]
Could you please post all questions on [our forums](https://nopcommerce.com/en/boards/)? We use GitHub for work items only
