### ISSUE TITLE
No files found matching exist in an asset /lib_npm/jquery/jquery.min.js

### ISSUE THREAD

**Issue by abodehq** [nopSolutions/nopCommerce#7201]
nopCommerce version: 4.7

Steps to reproduce the problem: 

i am trying to run  nopcommerce 4.7 using iis, the public site is working fine but the admin it gives an error :
No files found matching exist in an asset /lib_npm/jquery/jquery.min.js

System.IO.FileNotFoundException: No files found matching exist in an asset /lib_npm/jquery/jquery.min.js
   at WebOptimizer.Asset.ExpandGlobs(IAsset asset, IWebHostEnvironment env)
   at WebOptimizer.Asset.GenerateCacheKey(HttpContext context, IWebOptimizerOptions options)
   at Nop.Web.Framework.WebOptimizer.NopAssetHelper.CacheBusting(IAsset asset) in C:\Users\abedallateef.alqaisi\Desktop\ZainGitHubProjects\EshopWeb\Presentation\Nop.Web.Framework\WebOptimizer\NopAssetHelper.cs:line 125
   at Nop.Web.Framework.TagHelpers.Shared.NopScriptTagHelper.ProcessAsset(TagHelperOutput output) in C:\Users\abedallateef.alqaisi\Desktop\ZainGitHubProjects\EshopWeb\Presentation\Nop.Web.Framework\TagHelpers\Shared\NopScriptTagHelper.cs:line 118
   at Nop.Web.Framework.TagHelpers.Shared.NopScriptTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output) in C:\Users\abedallateef.alqaisi\Desktop\ZainGitHubProjects\EshopWeb\Presentation\Nop.Web.Framework\TagHelpers\Shared\NopScriptTagHelper.cs:line 152
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
   at AspNetCore.Areas_Admin_Views_Shared__AdminScripts.ExecuteAsync() in C:\Users\abedallateef.alqaisi\Desktop\ZainGitHubProjects\EshopWeb\Presentation\Nop.Web\Areas\Admin\Views\Shared\_AdminScripts.cshtml:line 57
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.RenderPartialCoreAsync(String partialViewName, Object model, ViewDataDictionary viewData, TextWriter writer)
   at AspNetCoreGeneratedDocument.Areas_Admin_Views_Shared__AdminLayout.<>c__DisplayClass30_0.<<ExecuteAsync>b__0>d.MoveNext() in C:\Users\abedallateef.alqaisi\Desktop\ZainGitHubProjects\EshopWeb\Presentation\Nop.Web\Areas\Admin\Views\Shared\_AdminLayout.cshtml:line 44
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
   at AspNetCoreGeneratedDocument.Areas_Admin_Views_Shared__AdminLayout.ExecuteAsync() in C:\Users\abedallateef.alqaisi\Desktop\ZainGitHubProjects\EshopWeb\Presentation\Nop.Web\Areas\Admin\Views\Shared\_AdminLayout.cshtml:line 35
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|28_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Nop.Services.Authentication.AuthenticationMiddleware.InvokeAsync(HttpContext context) in C:\Users\abedallateef.alqaisi\Desktop\ZainGitHubProjects\EshopWeb\Libraries\Nop.Services\Authentication\AuthenticationMiddleware.cs:line 86
   at WebMarkupMin.AspNetCore8.WebMarkupMinMiddleware.InvokeCore(HttpContext context, Boolean useMinification, Boolean useCompression)
   at WebMarkupMin.AspNetCore8.WebMarkupMinMiddleware.InvokeCore(HttpContext context, Boolean useMinification, Boolean useCompression)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Nop.Services.Installation.InstallUrlMiddleware.InvokeAsync(HttpContext context, IWebHelper webHelper) in C:\Users\abedallateef.alqaisi\Desktop\ZainGitHubProjects\EshopWeb\Libraries\Nop.Services\Installation\InstallUrlMiddleware.cs:line 50
   at Nop.Services.Common.KeepAliveMiddleware.InvokeAsync(HttpContext context, IWebHelper webHelper) in C:\Users\abedallateef.alqaisi\Desktop\ZainGitHubProjects\EshopWeb\Libraries\Nop.Services\Common\KeepAliveMiddleware.cs:line 47
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
   
   ---------------------------------------
   after checking the error , i found that this error happened because of this tag asp-location="None"
<script asp-location="None" src="~/lib_npm/jquery/jquery.min.js"></script>
which is located in 
Presentation\Nop.Web\Areas\Admin\Views\Shared\_AdminScripts.cshtml

after removing asp-location="None" it works fine!!!!

Note : in My local iis my url is like: http://localhost/eshopweb/Admin

please can you check <3

**Comment by AndreiMaz** [comment]
@exileDev also see https://www.nopcommerce.com/en/boards/topic/99078/error-installing-nopcommerce-470

**Comment by exileDev** [comment]
Closed #7201
