### ISSUE TITLE
SqlException: Cannot insert the value NULL into column 'CountryId', table 'databaseName.dbo.Customer'

### ISSUE THREAD

**Issue by nikitimi** [nopSolutions/nopCommerce#7342]
nopCommerce version: **4.5.0**

Steps to reproduce the problem: 
I don't know how to reproduce the problem, as I didn't modify the source code, nor the contents of the database nor the database schema. I have the similar problem with the following threads, but doesn't have any clear answers into it.

- [Thread One](https://www.nopcommerce.com/en/boards/topic/39954/cannot-insert-the-value-null-into-column).
- [Thread Two](https://www.nopcommerce.com/en/boards/topic/23309/error-on-table-mydb-cleandbocustomer).

---

# SqlException: Cannot insert the value NULL into column 'CountryId', table 'databaseName.dbo.Customer'; column does not allow nulls. INSERT fails. The statement has been terminated.

    Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, bool breakConnection, Action<Action> wrapCloseInAction)
    Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, bool callerHasConnectionLock, bool asyncClose)
    Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, out bool dataReady)
    Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
    Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
    Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, string resetOptionsString, bool isInternal, bool forDescribeParameterEncryption, bool shouldCacheForAlwaysEncrypted)
    Microsoft.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(bool isInternal, bool forDescribeParameterEncryption)
    Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, bool isInternal, string endMethod)
    Microsoft.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult)
    Microsoft.Data.SqlClient.SqlCommand.EndExecuteReaderAsync(IAsyncResult asyncResult)
    System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
    LinqToDB.Data.DataConnection.ExecuteScalarAsync(CancellationToken cancellationToken)
    LinqToDB.Data.DataConnection+QueryRunner.ExecuteScalarAsync(CancellationToken cancellationToken)
    LinqToDB.Linq.QueryRunner.ScalarQueryAsync(Query query, IDataContext dataContext, Expression expression, object[] ps, object[] preambles, CancellationToken cancellationToken)
    LinqToDB.Linq.QueryRunner.ScalarQueryAsync(Query query, IDataContext dataContext, Expression expression, object[] ps, object[] preambles, CancellationToken cancellationToken)
    LinqToDB.Linq.QueryRunner+InsertWithIdentity<T>.QueryAsync(IDataContext dataContext, T obj, InsertColumnFilter<T> columnFilter, string tableName, string serverName, string databaseName, string schemaName, TableOptions tableOptions, CancellationToken token)
    LinqToDB.DataExtensions.InsertWithInt32IdentityAsync<T>(IDataContext dataContext, T obj, InsertColumnFilter<T> columnFilter, string tableName, string databaseName, string schemaName, string serverName, TableOptions tableOptions, CancellationToken token)
    Nop.Data.DataProviders.BaseDataProvider.InsertEntityAsync<TEntity>(TEntity entity) in BaseDataProvider.cs

            /// A task that represents the asynchronous operation
            /// The task result contains the inserted entity
            /// </returns>
            public virtual async Task<TEntity> InsertEntityAsync<TEntity>(TEntity entity) where TEntity : BaseEntity
            {
                using var dataContext = CreateDataConnection();

                entity.Id = await dataContext.InsertWithInt32IdentityAsync(entity);

                return entity;
            }
            /// <summary>
            /// Inserts record into table. Returns inserted entity with identity
            /// </summary>

    Nop.Data.EntityRepository<TEntity>.InsertAsync(TEntity entity, bool publishEvent) in EntityRepository.cs
    Nop.Services.Customers.CustomerService.InsertGuestCustomerAsync() in CustomerService.cs

                //add to 'Guests' role
                var guestRole = await GetCustomerRoleBySystemNameAsync(NopCustomerDefaults.GuestsRoleName);
                if (guestRole == null)
                    throw new NopException("'Guests' role could not be loaded");

                await _customerRepository.InsertAsync(customer);

                await AddCustomerRoleMappingAsync(new CustomerCustomerRoleMapping { CustomerId = customer.Id, CustomerRoleId = guestRole.Id });
                return customer;
            }
            
    Nop.Web.Framework.WebWorkContext.SetCurrentCustomerAsync(Customer customer) in WebWorkContext.cs

                        }
                    }
                    if (customer == null || customer.Deleted || !customer.Active || customer.RequireReLogin)
                    {
                        //create guest if not exists

                        customer = await _customerService.InsertGuestCustomerAsync();

                    }
                }
                if (!customer.Deleted && customer.Active && !customer.RequireReLogin)
                {
                    //set customer cookie

    Nop.Web.Framework.WebWorkContext.GetCurrentCustomerAsync() in WebWorkContext.cs

            public virtual async Task<Customer> GetCurrentCustomerAsync()
            {
                //whether there is a cached value
                if (_cachedCustomer != null)
                    return _cachedCustomer;

                await SetCurrentCustomerAsync();

                return _cachedCustomer;
            }
            /// <summary>
            /// Sets the current customer

    Nop.Services.Security.PermissionService.AuthorizeAsync(PermissionRecord permission) in PermissionService.cs

            /// <returns>
            /// A task that represents the asynchronous operation
            /// The task result contains the rue - authorized; otherwise, false
            /// </returns>
            public virtual async Task<bool> AuthorizeAsync(PermissionRecord permission)
            {

                return await AuthorizeAsync(permission, await _workContext.GetCurrentCustomerAsync());

            }
            /// <summary>
            /// Authorize permission
            /// </summary>
            /// <param name="permission">Permission record</param>
    Nop.Web.Framework.Mvc.Filters.CheckAccessPublicStoreAttribute+CheckAccessPublicStoreFilter.CheckAccessPublicStoreAsync(AuthorizationFilterContext context) in CheckAccessPublicStoreAttribute.cs

                    //ignore filter (the action is available even if navigation is not allowed)
                    if (actionFilter?.IgnoreFilter ?? _ignoreFilter)
                        return;
                    //check whether current customer has access to a public store

                    if (await _permissionService.AuthorizeAsync(StandardPermissionProvider.PublicStoreAllowNavigation))

                        return;
                    //customer hasn't access to a public store
                    context.Result = new ChallengeResult();
                }
    Nop.Web.Framework.Mvc.Filters.CheckAccessPublicStoreAttribute+CheckAccessPublicStoreFilter.OnAuthorizationAsync(AuthorizationFilterContext context) in CheckAccessPublicStoreAttribute.cs

                /// Called early in the filter pipeline to confirm request is authorized
                /// </summary>
                /// <param name="context">Authorization filter context</param>
                /// <returns>A task that represents the asynchronous operation</returns>
                public async Task OnAuthorizationAsync(AuthorizationFilterContext context)
                {

                    await CheckAccessPublicStoreAsync(context);

                }
                #endregion
            }
            #endregion

    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
    Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
    Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
    Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
    Nop.Services.Authentication.AuthenticationMiddleware.InvokeAsync(HttpContext context) in AuthenticationMiddleware.cs

                    if (result?.Principal != null)
                    {
                        context.User = result.Principal;
                    }
                }

                await _next(context);

            }
            #endregion
        }
    }

    StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in MiniProfilerMiddleware.cs
    WebMarkupMin.AspNetCore6.WebMarkupMinMiddleware.ProcessAsync(HttpContext context, bool useMinification, bool useCompression)
    WebMarkupMin.AspNetCore6.WebMarkupMinMiddleware.ProcessAsync(HttpContext context, bool useMinification, bool useCompression)
    WebMarkupMin.AspNetCore6.WebMarkupMinMiddlewareBase.Invoke(HttpContext context)
    Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
    Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
    Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
    Nop.Services.Installation.InstallUrlMiddleware.InvokeAsync(HttpContext context, IWebHelper webHelper) in InstallUrlMiddleware.cs

                        context.Response.Redirect(installUrl);
                        return;
                    }
                }
                //or call the next middleware in the request pipeline

                await _next(context);

            }
            #endregion
        }
    }

    Nop.Services.Common.KeepAliveMiddleware.InvokeAsync(HttpContext context, IWebHelper webHelper) in KeepAliveMiddleware.cs

                    var keepAliveUrl = $"{webHelper.GetStoreLocation()}{NopCommonDefaults.KeepAlivePath}";
                    if (webHelper.GetThisPageUrl(false).StartsWith(keepAliveUrl, StringComparison.InvariantCultureIgnoreCase))
                        return;
                }
                //or call the next middleware in the request pipeline

                await _next(context);

            }
            #endregion
        }
    }

    Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
    Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
    Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
    Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
    Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
    Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
    Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

---

# Show raw exception details

    Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'CountryId', table 'databaseName.dbo.Customer'; column does not allow nulls. INSERT fails.
    
    The statement has been terminated.
    
       at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
    
       at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
    
       at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
    
       at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
    
       at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
    
       at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
    
       at Microsoft.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
    
       at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
    
       at Microsoft.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult)
    
       at Microsoft.Data.SqlClient.SqlCommand.EndExecuteReaderAsync(IAsyncResult asyncResult)
    
       at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
    
    --- End of stack trace from previous location ---
    
       at LinqToDB.Data.DataConnection.ExecuteScalarAsync(CancellationToken cancellationToken)
    
       at LinqToDB.Data.DataConnection.QueryRunner.ExecuteScalarAsync(CancellationToken cancellationToken)
    
       at LinqToDB.Linq.QueryRunner.ScalarQueryAsync(Query query, IDataContext dataContext, Expression expression, Object[] ps, Object[] preambles, CancellationToken cancellationToken)
    
       at LinqToDB.Linq.QueryRunner.ScalarQueryAsync(Query query, IDataContext dataContext, Expression expression, Object[] ps, Object[] preambles, CancellationToken cancellationToken)
    
       at LinqToDB.Linq.QueryRunner.InsertWithIdentity`1.QueryAsync(IDataContext dataContext, T obj, InsertColumnFilter`1 columnFilter, String tableName, String serverName, String databaseName, String schemaName, TableOptions tableOptions, CancellationToken token)
    
       at LinqToDB.DataExtensions.InsertWithInt32IdentityAsync[T](IDataContext dataContext, T obj, InsertColumnFilter`1 columnFilter, String tableName, String databaseName, String schemaName, String serverName, TableOptions tableOptions, CancellationToken token)
    
       at Nop.Data.DataProviders.BaseDataProvider.InsertEntityAsync[TEntity](TEntity entity) in C:\Users\GCCARRANZA\Desktop\Stork\stork.server\Libraries\Nop.Data\DataProviders\BaseDataProvider.cs:line 279
    
       at Nop.Data.EntityRepository`1.InsertAsync(TEntity entity, Boolean publishEvent) in C:\Users\GCCARRANZA\Desktop\Stork\stork.server\Libraries\Nop.Data\EntityRepository.cs:line 0
    
       at Nop.Services.Customers.CustomerService.InsertGuestCustomerAsync() in C:\Users\GCCARRANZA\Desktop\Stork\stork.server\Libraries\Nop.Services\Customers\CustomerService.cs:line 642
    
       at Nop.Web.Framework.WebWorkContext.SetCurrentCustomerAsync(Customer customer) in C:\Users\GCCARRANZA\Desktop\Stork\stork.server\Presentation\Nop.Web.Framework\WebWorkContext.cs:line 278
    
       at Nop.Web.Framework.WebWorkContext.GetCurrentCustomerAsync() in C:\Users\GCCARRANZA\Desktop\Stork\stork.server\Presentation\Nop.Web.Framework\WebWorkContext.cs:line 207
    
       at Nop.Services.Security.PermissionService.AuthorizeAsync(PermissionRecord permission) in C:\Users\GCCARRANZA\Desktop\Stork\stork.server\Libraries\Nop.Services\Security\PermissionService.cs:line 262
    
       at Nop.Web.Framework.Mvc.Filters.CheckAccessPublicStoreAttribute.CheckAccessPublicStoreFilter.CheckAccessPublicStoreAsync(AuthorizationFilterContext context) in C:\Users\GCCARRANZA\Desktop\Stork\stork.server\Presentation\Nop.Web.Framework\Mvc\Filters\CheckAccessPublicStoreAttribute.cs:line 90
    
       at Nop.Web.Framework.Mvc.Filters.CheckAccessPublicStoreAttribute.CheckAccessPublicStoreFilter.OnAuthorizationAsync(AuthorizationFilterContext context) in C:\Users\GCCARRANZA\Desktop\Stork\stork.server\Presentation\Nop.Web.Framework\Mvc\Filters\CheckAccessPublicStoreAttribute.cs:line 108
    
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
    
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
    
       at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
    
       at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
    
       at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
    
       at Nop.Services.Authentication.AuthenticationMiddleware.InvokeAsync(HttpContext context) in C:\Users\GCCARRANZA\Desktop\Stork\stork.server\Libraries\Nop.Services\Authentication\AuthenticationMiddleware.cs:line 94
    
       at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 103
    
       at WebMarkupMin.AspNetCore6.WebMarkupMinMiddleware.ProcessAsync(HttpContext context, Boolean useMinification, Boolean useCompression)
    
       at WebMarkupMin.AspNetCore6.WebMarkupMinMiddleware.ProcessAsync(HttpContext context, Boolean useMinification, Boolean useCompression)
    
       at WebMarkupMin.AspNetCore6.WebMarkupMinMiddlewareBase.Invoke(HttpContext context)
    
       at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
    
       at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
    
       at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
    
       at Nop.Services.Installation.InstallUrlMiddleware.InvokeAsync(HttpContext context, IWebHelper webHelper) in C:\Users\GCCARRANZA\Desktop\Stork\stork.server\Libraries\Nop.Services\Installation\InstallUrlMiddleware.cs:line 52
    
       at Nop.Services.Common.KeepAliveMiddleware.InvokeAsync(HttpContext context, IWebHelper webHelper) in C:\Users\GCCARRANZA\Desktop\Stork\stork.server\Libraries\Nop.Services\Common\KeepAliveMiddleware.cs:line 49
    
       at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
    
       at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
    
       at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
    
       at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
    
       at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
    
       at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
    
       at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
    
    ClientConnectionId:4dc1a610-caf5-45e3-9893-1d13847284d6
    
    Error Number:515,State:2,Class:16

**Comment by AndreiMaz** [comment]
> I don't know how to reproduce the problem

We also cannot reproduce it. We cannot help until you can provide a list of steps to reproduce it
